zcash/librustzcash

- .travis.yml
We need automated tests to merge commits by policy. This sets up travis temporarily until we configure our main CI to build and test this repository.
> Add travis testing support.

- .github/workflows/rust.yml
Enables running tests on Windows and macOS in addition to Ubuntu (which Travis CI provides).
> Add a GitHub Actions workflow

- zcash_client_backend/src/encoding.rs
> Unit tests for key encodings

- bellman/src/gadgets/uint32.rs
- zcash_client_backend/src/encoding.rs
> Doc link fixes

- zcash_proofs/src/sapling/prover.rs
- zcash_proofs/src/sapling/verifier.rs
Signed-off-by: Gregory Hill <gregorydhill@outlook.com>
Closes #79
> rename bvk to cv_sum

- zcash_client_backend/src/decrypt.rs
- zcash_client_backend/src/lib.rs
> zcash_client_backend::decrypt_transaction

- librustzcash/src/rustzcash.rs
- librustzcash/src/tests/mmr.rs
Addresses the remaining comments from #118.
> MMR API cleanups

- ff/ff_derive/src/lib.rs
> Constant-time field inversion in ff_derive using pow_vartime

- bellman/src/groth16/prover.rs
- bellman/src/groth16/tests/dummy_engine.rs
- bellman/src/groth16/verifier.rs
- bellman/src/multiexp.rs
- group/src/lib.rs
- group/src/tests/mod.rs
- pairing/benches/bls12_381/ec.rs
- pairing/src/bls12_381/ec.rs
- pairing/src/lib.rs
> Move Group operations to operator-backed traits

- bellman/src/gadgets/blake2s.rs
- librustzcash/src/rustzcash.rs
- zcash_client_backend/src/welding_rig.rs
- zcash_primitives/src/block/equihash.rs
- zcash_primitives/src/jubjub/edwards.rs
- zcash_primitives/src/merkle_tree.rs
- zcash_primitives/src/redjubjub.rs
- zcash_primitives/src/transaction/tests.rs
- zcash_proofs/src/sapling/prover.rs
Written while reading some of the code. Opinions on this are loose,
happy to accomodate in review.
> Addressing some trivial Rust option/iterator lints

- .github/workflows/ci.yml
- bls12_381/.github/workflows/ci.yml
- bls12_381/Cargo.toml
- bls12_381/README.md
- bls12_381/RELEASES.md
- bls12_381/src/g1.rs
- bls12_381/src/g2.rs
- bls12_381/src/notes/design.rs
- bls12_381/src/scalar.rs
Pulls in https://github.com/zkcrypto/bls12_381/commit/d0ea5d4958cae999dea1800207704171aa07a9ef
> Update bls12_381 subtree

- bellman/src/groth16/tests/dummy_engine.rs
- group/src/cofactor.rs
- group/src/lib.rs
- group/src/wnaf.rs
- pairing/src/bls12_381/ec.rs
Changes that have arisen from review of #245.
> Updates to group traits

- zcash_proofs/Cargo.toml
- zcash_proofs/benches/sapling.rs
Closes zcash/librustzcash#282.
> zcash_proof: Migrate benchmark to criterion

- zcash_client_backend/src/decrypt.rs
- zcash_client_backend/src/proto/mod.rs
- zcash_client_backend/src/wallet.rs
- zcash_client_sqlite/src/transact.rs
- zcash_primitives/Cargo.toml
- zcash_primitives/benches/note_decryption.rs
- zcash_primitives/src/note_encryption.rs
Closes zcash/librustzcash#273.
> Take epk as a jubjub::ExtendedPoint for note decryption

- zcash_primitives/src/note_encryption.rs
Some constants that are useful during testing.
> Export notesize constants

- zcash_client_sqlite/src/transact.rs
- zcash_extensions/src/transparent/demo.rs
- zcash_primitives/src/transaction/builder.rs
- zcash_primitives/src/transaction/components/amount.rs
Attempts to implement ZIP-313 in the least complex way. Full compliance may require not merging this until Canopy activation.
Closes related issues for downstream projects (once they update to librustzcash after this is merged):
- https://github.com/zcash/ZcashLightClientKit/issues/221 - Native iOS
- https://github.com/zcash/zcash-android-wallet-sdk/issues/174 - Native Android
> ZIP 313 Implementation

- zcash_primitives/src/transaction/builder.rs
- zcash_primitives/src/zip32.rs
- zcash_proofs/src/circuit/sprout/mod.rs
Minor simplifications, tool-aided by [comby-rust](https://github.com/huitseeker/comby-rust).
> Small cleanups

- zcash_primitives/proptest-regressions/transaction/tests.txt
- zcash_primitives/src/transaction/mod.rs
- zcash_primitives/src/transaction/sighash.rs
- zcash_primitives/src/transaction/tests.rs
More cleanup in preparation for transaction malleability fixes.
> Add TxVersion enum to make interacting with transaction version values safer.

- zcash_client_backend/src/data_api.rs
- zcash_client_backend/src/data_api/chain.rs
- zcash_client_backend/src/welding_rig.rs
- zcash_client_sqlite/src/error.rs
- zcash_client_sqlite/src/lib.rs
- zcash_client_sqlite/src/wallet.rs
- zcash_primitives/benches/note_decryption.rs
- zcash_primitives/src/note_encryption.rs
- zcash_primitives/src/primitives.rs
This includes making it possible to obtain a payment address from just the IVK + diversifier.
> Introduce SaplingIvk newtype & use IVKs where possible.

- zcash_client_sqlite/src/wallet.rs
Previously we were retrieving nullifiers for notes that were not
marked spent, but not checking against whether the spending
transaction had been included in a block.
> Retrieve nullifiers for all unconfirmed notes.

- zcash_client_backend/CHANGELOG.md
- zcash_primitives/CHANGELOG.md
> Add SaplingIvk newtype to changelogs.

- zcash_client_backend/Cargo.toml
- zcash_client_backend/src/data_api.rs
- zcash_client_backend/src/data_api/chain.rs
- zcash_client_backend/src/encoding.rs
- zcash_client_backend/src/keys.rs
- zcash_client_backend/src/wallet.rs
- zcash_client_backend/src/welding_rig.rs
- zcash_client_backend/src/zip321.rs
- zcash_client_sqlite/CHANGELOG.md
- zcash_client_sqlite/Cargo.toml
- zcash_client_sqlite/src/wallet.rs
- zcash_client_sqlite/src/wallet/transact.rs
- zcash_primitives/src/constants/regtest.rs
- zcash_primitives/src/memo.rs
- zcash_primitives/src/transaction/builder.rs
- zcash_primitives/src/transaction/components.rs
- zcash_primitives/src/transaction/sighash.rs
> Release 0.5 preparations

- zcash_primitives/src/transaction/components/orchard.rs
- zcash_primitives/src/transaction/mod.rs
These will be used by `zcashd` for handling the Orchard component of v5 transactions.
> Extract ZIP 225 Orchard bundle parsing and serialization into helpers

- zcash_history/src/version.rs
- zcash_primitives/src/transaction/components/orchard.rs
Both of these complaints are spurious in our case, so I'm merely marking them as ignored.
> Fix clippy complaints

- Cargo.toml
- components/zcash_note_encryption/src/batch.rs
- components/zcash_note_encryption/src/lib.rs
- zcash_primitives/benches/note_decryption.rs
- zcash_primitives/src/sapling/note_encryption.rs
> Batch note decryption

- zcash_primitives/src/zip32.rs
Sapling address generation depends only on an FVK and
a diversifier key. For the purpose of unified full viewing
keys, we need to break the dependence upon Sapling extended
full viewing keys, so this makes the address generation
methods of SaplingExtendedFullViewingKey usable without
coupling them to the ability to derive child full viewing keys.
> Factors out sapling address generation from SaplingExtendedFullViewingKey

- Cargo.toml
- components/zcash_note_encryption/CHANGELOG.md
- components/zcash_note_encryption/Cargo.toml
- components/zcash_note_encryption/LICENSE-APACHE
- components/zcash_note_encryption/LICENSE-MIT
- components/zcash_note_encryption/README.md
- components/zcash_note_encryption/src/lib.rs
- zcash_client_backend/Cargo.toml
- zcash_extensions/Cargo.toml
- zcash_primitives/Cargo.toml
Closes zcash/librustzcash#457.
> `zcash_note_encryption 0.1.0`

- zcash_primitives/CHANGELOG.md
- zcash_primitives/src/zip32.rs
As specified in https://github.com/zcash/zips/pull/576.
> Derive Sapling internal keys.

- .github/workflows/ci.yml
> Use clippy beta instead of nightly

- Cargo.toml
- zcash_client_backend/Cargo.toml
- zcash_client_sqlite/Cargo.toml
- zcash_primitives/Cargo.toml
- zcash_primitives/src/legacy/keys.rs
- zcash_primitives/src/transaction/components/transparent/builder.rs
This can be done any time; this PR is currently targeted at the non-consensus changes branch but could be included in anything that this merges to.
Fixes #520
> Update to secp256k1 v0.21

- zcash_primitives/src/merkle_tree.rs
- zcash_primitives/src/merkle_tree/incremental.rs
- zcash_primitives/src/transaction/components/sapling/builder.rs
> Add conversion from incrementalmerkletree::bridgetree::Frontier -> CommitmentTree

- components/f4jumble/Cargo.toml
- components/f4jumble/src/lib.rs
> Add documentation to `f4jumble` crate

- zcash_client_backend/CHANGELOG.md
- zcash_client_backend/Cargo.toml
- zcash_client_backend/src/address.rs
- zcash_client_backend/src/data_api/wallet.rs
- zcash_client_backend/src/keys.rs
- zcash_client_backend/src/zip321.rs
- zcash_client_sqlite/src/lib.rs
Part of zcash/librustzcash#387.
> Add `RecipientAddress::Unified`

- zcash_client_backend/CHANGELOG.md
- zcash_client_backend/src/address.rs
- zcash_client_backend/src/data_api.rs
- zcash_client_backend/src/data_api/chain.rs
- zcash_client_backend/src/data_api/wallet.rs
- zcash_client_backend/src/decrypt.rs
- zcash_client_backend/src/keys.rs
- zcash_client_backend/src/welding_rig.rs
- zcash_client_sqlite/CHANGELOG.md
- zcash_client_sqlite/src/chain.rs
- zcash_client_sqlite/src/lib.rs
- zcash_client_sqlite/src/wallet.rs
- zcash_client_sqlite/src/wallet/init.rs
- zcash_client_sqlite/src/wallet/transact.rs
- zcash_primitives/CHANGELOG.md
- zcash_primitives/src/sapling/keys.rs
- zcash_primitives/src/zip32.rs
Closes zcash/librustzcash#387.
> `zcash_client_*`: Migrate from `ExtendedFullViewingKey` to `UnifiedFullViewingKey`

- README.md
- components/zcash_note_encryption/README.md
- zcash_client_backend/README.md
- zcash_client_sqlite/README.md
- zcash_extensions/README.md
- zcash_primitives/README.md
- zcash_proofs/README.md
fixes #576
Signed-off-by: Daira Hopwood <daira@jacaranda.org>
> Projects that rely on BOSL exceptions should say that they do

- zcash_client_backend/src/keys.rs
- zcash_client_sqlite/src/lib.rs
- zcash_client_sqlite/src/wallet/init.rs
- zcash_client_sqlite/src/wallet/transact.rs
> Fix account key init

- zcash_client_backend/src/address.rs
Get the Orchard Address from UA
> Return orchard address from UA

- zcash_client_backend/Cargo.toml
- zcash_client_backend/src/data_api/chain.rs
- zcash_client_backend/src/lib.rs
- zcash_client_backend/src/scan.rs
- zcash_client_backend/src/welding_rig.rs
- zcash_primitives/src/transaction/components/sapling.rs
This ports/reimplements the batched decryption approach used in zcashd to implement light wallet scanning.
> Implement parallel, batched trial decryption in wallet scanning.

- zcash_client_backend/src/keys.rs
This ensures that the resulting UFVKs and UAs also contain Orchard components.
> zcash_client_backend: Generate Orchard component for USKs

- zcash_client_sqlite/src/chain.rs
The `MAX` SQLite function returns `null` when the table is empty. The code was expecting zero rows to be returned in this case, and was trying to parse the `null` as an integer.
> zcash_client_sqlite: Fix `FsBlockDb::get_max_cached_height`

- zcash_client_backend/Cargo.toml
- zcash_client_backend/src/scan.rs
Ported from https://github.com/zcash/zcash/pull/6172.
> Batch scanner memory reduction

- zcash_client_sqlite/src/wallet/init/migrations/add_transaction_views.rs
The previous approach to UTXO handling involved UTXO data being deleted from the wallet after the relevant UTXOs had been spent. However, this means that we can no longer accurately compute transaction fees for the transactions spending those UTXOs. However, since the transaction fee has been a constant 1000 ZAT for the life of any wallet where this issue might occur, we can just ignore those cases and assume the 1000 ZAT fee.
> Allow spent UTXOs to be absent in migrations when adding tx fee.

- zcash_client_backend/CHANGELOG.md
- zcash_client_backend/src/data_api.rs
- zcash_client_backend/src/data_api/error.rs
- zcash_client_backend/src/data_api/wallet.rs
- zcash_client_sqlite/src/lib.rs
- zcash_client_sqlite/src/wallet.rs
- zcash_client_sqlite/src/wallet/transact.rs
> Use unified spending keys for spends & shielding.

- zcash_client_sqlite/src/wallet/init.rs
- zcash_client_sqlite/src/wallet/init/migrations.rs
- zcash_client_sqlite/src/wallet/init/migrations/add_transaction_views.rs
- zcash_client_sqlite/src/wallet/init/migrations/sent_notes_to_internal.rs
- zcash_client_sqlite/src/wallet/init/migrations/ufvk_support.rs
This adds sent and received note count information, transaction fees, account information, and makes the information returned about sent notes and received notes consistent with one another.
> Add more information to v_transactions, v_sent_tx, and v_received_tx

- zcash_client_backend/src/zip321.rs
> Parse ZIP 321 URIs without query parameters

- zcash_client_sqlite/src/wallet.rs
- zcash_client_sqlite/src/wallet/init.rs
- zcash_client_sqlite/src/wallet/transact.rs
- zcash_primitives/Cargo.toml
- zcash_primitives/src/zip32.rs
> Fix transparent balance error when the wallet is empty.

- zcash_client_backend/src/decrypt.rs
- zcash_client_backend/src/proto.rs
- zcash_client_sqlite/src/lib.rs
- zcash_client_sqlite/src/wallet/transact.rs
- zcash_primitives/CHANGELOG.md
- zcash_primitives/benches/note_decryption.rs
- zcash_primitives/src/sapling.rs
- zcash_primitives/src/sapling/note_encryption.rs
- zcash_primitives/src/sapling/prover.rs
- zcash_primitives/src/sapling/value.rs
- zcash_primitives/src/sapling/value/sums.rs
- zcash_primitives/src/transaction/builder.rs
- zcash_primitives/src/transaction/components/sapling.rs
- zcash_primitives/src/transaction/components/sapling/builder.rs
- zcash_primitives/src/transaction/mod.rs
- zcash_primitives/src/transaction/sighash_v4.rs
- zcash_primitives/src/transaction/txid.rs
- zcash_proofs/CHANGELOG.md
- zcash_proofs/benches/sapling.rs
- zcash_proofs/src/circuit/sapling.rs
- zcash_proofs/src/prover.rs
- zcash_proofs/src/sapling/mod.rs
- zcash_proofs/src/sapling/prover.rs
- zcash_proofs/src/sapling/verifier.rs
- zcash_proofs/src/sapling/verifier/batch.rs
- zcash_proofs/src/sapling/verifier/single.rs
> Improve Sapling type safety

- zcash_client_sqlite/src/chain/init.rs
- zcash_client_sqlite/src/lib.rs
> Add a note about metadata database initialization to `FsBlockDb::for_path`

- zcash_client_backend/CHANGELOG.md
- zcash_client_backend/Cargo.toml
- zcash_client_sqlite/CHANGELOG.md
- zcash_client_sqlite/Cargo.toml
- zcash_extensions/Cargo.toml
- zcash_primitives/CHANGELOG.md
- zcash_primitives/Cargo.toml
- zcash_proofs/CHANGELOG.md
- zcash_proofs/Cargo.toml
> `zcash_primitives 0.10.0`, `zcash_proofs 0.10.0`, `zcash_client_backend 0.7.0`, `zcash_client_sqlite 0.5.0`

- zcash_client_backend/src/fees/zip317.rs
> Ensure that Sapling padding outputs are taken account in ZIP 317 change computation.

- zcash_proofs/src/hashreader.rs
Closes https://github.com/zcash/librustzcash/issues/786 by changing the type of `byte_count` from `usize` to `u64`.
> Fix a theoretical possibility of overflow leading to panic

- zcash_client_backend/src/fees/fixed.rs
- zcash_client_sqlite/src/wallet/transact.rs
- zcash_extensions/src/transparent/demo.rs
- zcash_primitives/CHANGELOG.md
- zcash_primitives/src/transaction/builder.rs
- zcash_primitives/src/transaction/components/amount.rs
This makes the default fee equal to the minimum possible zip317 fee.
> Update DEFAULT_FEE to 10_000 from 1000

- zcash_client_backend/CHANGELOG.md
- zcash_client_backend/Cargo.toml
- zcash_client_sqlite/CHANGELOG.md
- zcash_client_sqlite/Cargo.toml
- zcash_primitives/CHANGELOG.md
- zcash_primitives/Cargo.toml
Closes zcash/librustzcash#823.
> Migrate to `secp256k1 0.26`, `hdwallet 0.4`

- zcash_client_sqlite/src/wallet/transact.rs
- zcash_primitives/src/transaction/builder.rs
as specified in <https://zips.z.cash/zip-0203#changes-for-blossom>. fixes #837
> Update `DEFAULT_TX_EXPIRY_DELTA` to 40 blocks

- zcash_client_backend/CHANGELOG.md
- zcash_client_backend/src/data_api.rs
- zcash_client_backend/src/data_api/chain.rs
- zcash_client_sqlite/src/lib.rs
- zcash_client_sqlite/src/wallet/commitment_tree.rs
> Add interfaces & support for subtree root insertion.

- zcash_client_backend/CHANGELOG.md
- zcash_client_backend/src/data_api.rs
- zcash_client_backend/src/keys.rs
- zcash_client_sqlite/Cargo.toml
- zcash_client_sqlite/src/chain.rs
- zcash_client_sqlite/src/lib.rs
- zcash_client_sqlite/src/testing.rs
- zcash_client_sqlite/src/wallet.rs
- zcash_client_sqlite/src/wallet/commitment_tree.rs
- zcash_client_sqlite/src/wallet/init.rs
- zcash_client_sqlite/src/wallet/init/migrations/add_transaction_views.rs
- zcash_client_sqlite/src/wallet/init/migrations/received_notes_nullable_nf.rs
- zcash_client_sqlite/src/wallet/init/migrations/v_transactions_net.rs
- zcash_client_sqlite/src/wallet/sapling.rs
- zcash_client_sqlite/src/wallet/scanning.rs
Review this commit-by-commit, or with whitespace changes ignored.
> Test refactorings in preparation for #907

- zcash_client_sqlite/src/wallet/commitment_tree.rs
> Check for potential discontinuities when inserting into the `*_tree_shards` table

- zcash_client_backend/CHANGELOG.md
- zcash_client_backend/src/data_api.rs
- zcash_client_sqlite/src/lib.rs
- zcash_client_sqlite/src/wallet.rs
- zcash_client_sqlite/src/wallet/sapling.rs
> zcash_client_backend: Add `WalletRead::block_max_scanned`

- zcash_client_sqlite/src/wallet/commitment_tree.rs
The previous code was checking that the existing shard range was at least partially inside the proposed insertion range, but this didn't handle the case where the proposed insertion range was fully contained by the existing shard range.
> zcash_client_sqlite: Fix bug in `check_shard_discontinuity`

- zcash_client_sqlite/src/wallet/scanning.rs
This modifies `update_chain_tip` and `scan_complete` to ensure that newly created scan ranged do not extend below the wallet birthday height.
Fixes #947
> zcash_client_sqlite: Bound creation of scan ranges on wallet birthday.

- zcash_client_backend/src/data_api.rs
- zcash_client_sqlite/src/wallet.rs
> zcash_client_sqlite: Return a balance for every account from `get_wallet_summary`

- zcash_client_backend/CHANGELOG.md
- zcash_client_backend/Cargo.toml
- zcash_client_sqlite/CHANGELOG.md
- zcash_client_sqlite/Cargo.toml
- zcash_extensions/Cargo.toml
- zcash_primitives/CHANGELOG.md
- zcash_primitives/Cargo.toml
- zcash_proofs/CHANGELOG.md
- zcash_proofs/Cargo.toml
> Spend-before-Sync release candidates

- zcash_client_sqlite/src/testing.rs
- zcash_client_sqlite/src/wallet/sapling.rs
- zcash_primitives/CHANGELOG.md
- zcash_primitives/src/transaction/components/amount.rs
> Merge test harness fixes to the release candidate branch

- .github/workflows/ci.yml
- zcash_client_sqlite/src/wallet/init.rs
- zcash_client_sqlite/src/wallet/init/migrations.rs
- zcash_client_sqlite/src/wallet/init/migrations/add_transaction_views.rs
- zcash_client_sqlite/src/wallet/init/migrations/add_utxo_account.rs
- zcash_client_sqlite/src/wallet/init/migrations/addresses_table.rs
- zcash_client_sqlite/src/wallet/init/migrations/initial_setup.rs
- zcash_client_sqlite/src/wallet/init/migrations/received_notes_nullable_nf.rs
- zcash_client_sqlite/src/wallet/init/migrations/sent_notes_to_internal.rs
- zcash_client_sqlite/src/wallet/init/migrations/shardtree_support.rs
- zcash_client_sqlite/src/wallet/init/migrations/ufvk_support.rs
- zcash_client_sqlite/src/wallet/init/migrations/utxos_table.rs
- zcash_client_sqlite/src/wallet/init/migrations/v_transactions_net.rs
- zcash_client_sqlite/src/wallet/init/migrations/v_transactions_shielding_balance.rs
This fixes a bug in v_transactions whereby shielding transactions displayed an incorrect balance.
> zcash_client_sqlite: Include spent utxos in v_transactions net value.

- zcash_primitives/CHANGELOG.md
- zcash_primitives/src/sapling/prover.rs
- zcash_proofs/CHANGELOG.md
- zcash_proofs/src/lib.rs
- zcash_proofs/src/prover.rs
- zcash_proofs/src/sapling/prover.rs
Part of #752 (maybe closes it, to be determined by what #741 requires).
Conflicts with #999 (whichever is merged later will be rebased).
> Separate Sapling provers

- zcash_client_backend/src/fees.rs
- zcash_primitives/src/transaction/components/transparent/builder.rs
- zcash_primitives/src/transaction/components/transparent/fees.rs
@nuttycom here're some debug attributes
> add Debug to transaction builder-reported types

- zcash_primitives/CHANGELOG.md
- zcash_primitives/src/sapling/circuit.rs
- zcash_primitives/src/sapling/keys.rs
- zcash_primitives/src/transaction/components/sapling.rs
Also includes a few new `Clone` and `Debug` impls we need.
Part of #741.
> Changes to Sapling bundle mapping

- zcash_client_backend/CHANGELOG.md
- zcash_client_backend/src/data_api.rs
- zcash_client_backend/src/data_api/error.rs
- zcash_client_backend/src/data_api/wallet.rs
- zcash_client_backend/src/data_api/wallet/input_selection.rs
- zcash_client_backend/src/fees.rs
- zcash_client_backend/src/fees/fixed.rs
- zcash_client_backend/src/fees/zip317.rs
- zcash_client_backend/src/wallet.rs
- zcash_client_backend/src/zip321.rs
- zcash_client_sqlite/src/chain.rs
- zcash_client_sqlite/src/lib.rs
- zcash_client_sqlite/src/wallet.rs
- zcash_client_sqlite/src/wallet/init/migrations/add_transaction_views.rs
- zcash_client_sqlite/src/wallet/sapling.rs
- zcash_extensions/src/transparent/demo.rs
- zcash_primitives/CHANGELOG.md
- zcash_primitives/src/transaction/builder.rs
- zcash_primitives/src/transaction/components/amount.rs
- zcash_primitives/src/transaction/components/sapling/builder.rs
- zcash_primitives/src/transaction/components/sapling/fees.rs
- zcash_primitives/src/transaction/components/transparent.rs
- zcash_primitives/src/transaction/components/transparent/builder.rs
- zcash_primitives/src/transaction/components/transparent/fees.rs
- zcash_primitives/src/transaction/components/tze.rs
- zcash_primitives/src/transaction/sighash.rs
- zcash_primitives/src/transaction/tests.rs
Builds atop #1012 
Review of this PR is slightly easier if you ignore whitespace.
> Use `NonNegativeAmount` for note and UTXO value fields

- zcash_client_backend/src/data_api/error.rs
- zcash_client_backend/src/proto.rs
- zcash_client_backend/src/scanning.rs
- zcash_primitives/CHANGELOG.md
- zcash_primitives/benches/note_decryption.rs
- zcash_primitives/src/sapling.rs
- zcash_primitives/src/sapling/builder.rs
- zcash_primitives/src/sapling/bundle.rs
- zcash_primitives/src/sapling/note_encryption.rs
- zcash_primitives/src/sapling/prover.rs
- zcash_primitives/src/sapling/value.rs
- zcash_primitives/src/sapling/verifier/batch.rs
- zcash_primitives/src/transaction/builder.rs
- zcash_primitives/src/transaction/components.rs
- zcash_primitives/src/transaction/components/sapling.rs
- zcash_primitives/src/transaction/mod.rs
- zcash_primitives/src/transaction/sighash.rs
- zcash_primitives/src/transaction/sighash_v4.rs
- zcash_primitives/src/transaction/tests.rs
- zcash_primitives/src/transaction/txid.rs
- zcash_proofs/src/prover.rs
> Refactor Sapling components and builder into `zcash_primitives::sapling`

- zcash_client_backend/examples/diversify-address.rs
- zcash_client_backend/src/decrypt.rs
- zcash_client_backend/src/encoding.rs
- zcash_client_backend/src/scanning.rs
- zcash_client_backend/src/wallet.rs
- zcash_client_sqlite/src/chain.rs
- zcash_client_sqlite/src/testing.rs
- zcash_client_sqlite/src/wallet.rs
- zcash_client_sqlite/src/wallet/sapling.rs
- zcash_client_sqlite/src/wallet/scanning.rs
- zcash_extensions/src/transparent/demo.rs
- zcash_primitives/CHANGELOG.md
- zcash_primitives/benches/note_decryption.rs
- zcash_primitives/src/sapling/builder.rs
- zcash_primitives/src/sapling/bundle.rs
- zcash_primitives/src/sapling/circuit.rs
- zcash_primitives/src/sapling/note_encryption.rs
- zcash_primitives/src/sapling/prover.rs
- zcash_primitives/src/transaction/builder.rs
> More Sapling cleanups

- zcash_client_backend/CHANGELOG.md
- zcash_client_backend/src/address.rs
- zcash_client_backend/src/data_api/wallet.rs
- zcash_client_backend/src/data_api/wallet/input_selection.rs
- zcash_client_backend/src/keys.rs
- zcash_client_backend/src/zip321.rs
- zcash_client_sqlite/src/chain.rs
- zcash_client_sqlite/src/testing.rs
- zcash_client_sqlite/src/wallet.rs
- zcash_client_sqlite/src/wallet/init.rs
- zcash_client_sqlite/src/wallet/init/migrations/addresses_table.rs
- zcash_client_sqlite/src/wallet/init/migrations/ufvk_support.rs
- zcash_client_sqlite/src/wallet/sapling.rs
Also, rename `Address::Shielded` to `Address::Sapling`
This addresses an old `TODO`, now's as good a time to do it as any.
> zcash_client_backend: Rename `RecipientAddress` to `Address`

- .github/workflows/ci.yml
Closes zcash/librustzcash#1098.
> CI: Add lint to check protobuf consistency with generated files

- .github/actions/prepare/action.yml
- .github/workflows/book.yml
- .github/workflows/ci.yml
Part of zcash/librustzcash#1123.
> CI: Replace `--all-features` with common feature config

- zcash_client_sqlite/src/wallet/init/migrations/receiving_key_scopes.rs
> receiving_key_scopes migration: Fall back to note commitment matching for scope determination

- zcash_client_backend/src/zip321.rs
These tests appear to have been broken by #1139; it's not clear why CI passed on that at the time.
> zcash_client_backend: Fix broken `zip321` tests.

- zcash_client_backend/src/data_api/chain.rs
- zcash_client_backend/src/scan.rs
- zcash_client_backend/src/scanning.rs
> zcash_client_backend: Extend `BatchRunner` to support full outputs

- zcash_client_backend/Cargo.toml
- zcash_client_backend/src/data_api/wallet.rs
- zcash_client_sqlite/Cargo.toml
- zcash_keys/Cargo.toml
- zcash_keys/src/address.rs
- zcash_keys/src/encoding.rs
- zcash_keys/src/keys.rs
> zcash_keys: Add `sapling` and `transparent` feature flags.

- zcash_client_backend/CHANGELOG.md
- zcash_client_backend/src/data_api.rs
- zcash_client_backend/src/data_api/scanning.rs
- zcash_client_backend/src/data_api/wallet.rs
- zcash_client_sqlite/src/testing.rs
> zcash_client_backend: Add documentation for the `data_api` module.

- Cargo.lock
- Cargo.toml
- zcash_client_backend/CHANGELOG.md
- zcash_client_backend/src/data_api.rs
- zcash_client_backend/src/data_api/error.rs
- zcash_client_backend/src/data_api/wallet.rs
- zcash_client_sqlite/CHANGELOG.md
- zcash_client_sqlite/Cargo.toml
- zcash_client_sqlite/src/chain.rs
- zcash_client_sqlite/src/error.rs
- zcash_client_sqlite/src/lib.rs
- zcash_client_sqlite/src/wallet.rs
- zcash_client_sqlite/src/wallet/init.rs
- zcash_client_sqlite/src/wallet/init/migrations.rs
- zcash_client_sqlite/src/wallet/init/migrations/add_utxo_account.rs
- zcash_client_sqlite/src/wallet/init/migrations/addresses_table.rs
- zcash_client_sqlite/src/wallet/init/migrations/full_account_ids.rs
- zcash_client_sqlite/src/wallet/init/migrations/receiving_key_scopes.rs
- zcash_client_sqlite/src/wallet/init/migrations/ufvk_support.rs
- zcash_client_sqlite/src/wallet/sapling.rs
- zcash_keys/CHANGELOG.md
- zcash_keys/Cargo.toml
- zcash_keys/src/keys.rs
> zcash_client_sqlite: Rework accounts to support imported viewing keys

- zcash_client_backend/CHANGELOG.md
- zcash_client_backend/src/data_api.rs
- zcash_client_sqlite/src/lib.rs
- zcash_client_sqlite/src/testing.rs
- zcash_client_sqlite/src/testing/pool.rs
- zcash_client_sqlite/src/wallet.rs
- zcash_client_sqlite/src/wallet/commitment_tree.rs
- zcash_client_sqlite/src/wallet/init.rs
- zcash_client_sqlite/src/wallet/scanning.rs
> Fix update_chain_tip_unstable_max_scanned tests.

- zcash_client_sqlite/src/lib.rs
- zcash_client_sqlite/src/testing/pool.rs
- zcash_client_sqlite/src/wallet.rs
- zcash_client_sqlite/src/wallet/common.rs
- zcash_client_sqlite/src/wallet/init.rs
- zcash_client_sqlite/src/wallet/init/migrations/full_account_ids.rs
- zcash_client_sqlite/src/wallet/init/migrations/orchard_received_notes.rs
- zcash_client_sqlite/src/wallet/orchard.rs
- zcash_client_sqlite/src/wallet/sapling.rs
> zcash_client_sqlite: Fix balance in expired unmined transaction history.

- Cargo.lock
- zcash_client_sqlite/CHANGELOG.md
- zcash_client_sqlite/Cargo.toml
> zcash_client_sqlite 0.10.2

- .github/workflows/aggregate-audits.yml
Fixes https://github.com/zcash/librustzcash/actions/runs/8853688391/job/24315095768.
> CI: Add explicit token to GitHub CLI usage

- Cargo.lock
- Cargo.toml
- zcash_client_backend/src/data_api/chain.rs
- zcash_client_backend/src/scanning.rs
- zcash_client_backend/src/serialization/shardtree.rs
- zcash_client_sqlite/Cargo.toml
- zcash_client_sqlite/src/lib.rs
- zcash_client_sqlite/src/testing.rs
- zcash_client_sqlite/src/testing/pool.rs
- zcash_client_sqlite/src/wallet.rs
- zcash_client_sqlite/src/wallet/commitment_tree.rs
- zcash_client_sqlite/src/wallet/init/migrations/shardtree_support.rs
- zcash_client_sqlite/src/wallet/scanning.rs
> `zcash_client_sqlite` Fix error related to commitment tree frontier insertions.

- zcash_client_sqlite/src/lib.rs
Closes zcash/librustzcash#1273.
> zcash_client_sqlite: Fix `--no-default-features` compilation

- zcash_client_backend/CHANGELOG.md
- zcash_client_backend/src/data_api.rs
- zcash_client_backend/src/decrypt.rs
- zcash_client_backend/src/wallet.rs
- zcash_client_sqlite/src/lib.rs
- zcash_client_sqlite/src/testing/pool.rs
- zcash_client_sqlite/src/wallet/transparent.rs
- zcash_primitives/src/legacy.rs
> zcash_client_sqlite: Store received UTXOs in `store_decrypted_tx`

- zcash_client_backend/src/data_api/wallet.rs
- zcash_client_sqlite/src/wallet/init/migrations/ephemeral_addresses.rs
> Don't store transactions when creation of a subsequent transaction fails

- zcash_client_sqlite/CHANGELOG.md
- zcash_client_sqlite/src/testing.rs
- zcash_client_sqlite/src/testing/pool.rs
- zcash_client_sqlite/src/wallet/db.rs
- zcash_client_sqlite/src/wallet/init/migrations/utxos_to_txos.rs
Closes zcash/librustzcash#1046.
> zcash_client_sqlite: Add `is_shielding` to `v_transactions` view

- zcash_client_backend/src/scanning.rs
small error I noticed while reading through scanning.rs
> corrected pool type for scan error

- Cargo.lock
- Cargo.toml
- supply-chain/audits.toml
- supply-chain/config.toml
- supply-chain/imports.lock
- zcash_primitives/CHANGELOG.md
* sapling-crypto 0.2
* orchard 0.9
* incrementalmerketree 0.6
* shardtree 0.4
> zcash_primitivies: Update zcash-specific dependencies.

- zcash_keys/CHANGELOG.md
- zcash_keys/Cargo.toml
- zcash_keys/src/keys.rs
> [#1477] Allow Orchard-only UFVK be created from an Orchard FVK

- Cargo.lock
- Cargo.toml
- supply-chain/audits.toml
- supply-chain/imports.lock
- zcash_client_backend/CHANGELOG.md
- zcash_client_backend/Cargo.toml
> release zcash_client_backend version 0.13.0

- Cargo.lock
- supply-chain/imports.lock
- zcash_client_sqlite/CHANGELOG.md
- zcash_client_sqlite/Cargo.toml
> release zcash_client_sqlite version 0.11.0

- .github/workflows/audits.yml
- .github/workflows/ci.yml
> [Do not merge] CI: Move expensive tests to another task

- components/f4jumble/src/test_vectors.rs
- components/zcash_address/src/kind/unified/address/test_vectors.rs
- components/zcash_address/src/lib.rs
- components/zcash_protocol/src/consensus.rs
- components/zcash_protocol/src/constants/mainnet.rs
- components/zcash_protocol/src/constants/testnet.rs
- zcash_primitives/src/transaction/tests/data.rs
- zcash_transparent/src/test_vectors.rs
Hi! I fixed multiple broken links across several files in the repository. The changes primarily update references to test vectors and documentation that have moved locations in the Zcash ecosystem.
> chore: fixed dead links

- zcash_client_sqlite/src/wallet.rs
This should reduce the amount by which the boundary between scan and recovery progress moves over time, instead of it following the max-scanned height upward on first scan after initial wallet recovery.
Closes zcash/librustzcash#1772.
> zcash_client_sqlite: Extrapolate recover-until size instead of coercing

- zcash_client_sqlite/src/wallet/init/migrations/receiving_key_scopes.rs
fixes #1900 (see https://github.com/zcash/librustzcash/issues/1900#issuecomment-3172838601)
> Fix building tests with "multicore" disabled and "transparent-inputs" enabled

- zcash_client_backend/src/data_api/testing/pool.rs
- zcash_client_sqlite/src/testing/pool.rs
- zcash_client_sqlite/src/wallet/orchard.rs
- zcash_client_sqlite/src/wallet/sapling.rs
> add tests that spend all available funds manually

- Cargo.lock
- supply-chain/config.toml
- supply-chain/imports.lock
- zcash_client_sqlite/CHANGELOG.md
- zcash_client_sqlite/Cargo.toml
- zcash_client_sqlite/src/wallet/db.rs
- zcash_client_sqlite/src/wallet/init/migrations.rs
- zcash_client_sqlite/src/wallet/init/migrations/fix_v_transactions_expired_unmined.rs
> zcash_client_sqlite: fix possible false positive in `v_transactions.expired_unmined` determination.

- zcash_client_sqlite/CHANGELOG.md
- zcash_client_sqlite/src/wallet/db.rs
- zcash_client_sqlite/src/wallet/init/migrations.rs
- zcash_client_sqlite/src/wallet/init/migrations/v_tx_outputs_return_addrs.rs
> zcash_client_sqlite: Add address & diversifier index information to `v_tx_outputs`.

- zcash_client_sqlite/CHANGELOG.md
- zcash_client_sqlite/src/wallet.rs
- zcash_client_sqlite/src/wallet/init/migrations/sapling_memo_consistency.rs
Part of https://github.com/zcash/wallet/issues/269.
> zcash_client_sqlite: Use `mined_height` column in more places

- zcash_client_memory/Cargo.toml
- zcash_client_sqlite/src/wallet/common.rs
- zcash_client_sqlite/src/wallet/init/migrations.rs
- zcash_client_sqlite/src/wallet/init/migrations/v_tx_outputs_return_addrs.rs
> zcash_client_sqlite: Bugfixes
