zcash/librustzcash

include/librustzcash.h
src/rustzcash.rs
src/tests/key_components.rs

- `librustzcash_to_scalar`
- `librustzcash_ask_to_ak`
- `librustzcash_nsk_to_nk`
- `librustzcash_crh_ivk`
- `librustzcash_check_diversifier`
- `librustzcash_ivk_to_pkd`

librustzcash APIs for wallet key manipulation

---

Cargo.lock
Cargo.toml
include/librustzcash.h
src/rustzcash.rs

Written alongside @gtank.
This C API allows you to construct Sapling proofs.
1. Create a context with `librustzcash_sapling_proving_ctx_init`. This context contains the current value of `bsk`.
2. Create Spend proofs with `librustzcash_sapling_spend_proof`. Give it the witness and it'll output `cv` (`rcv` is chosen randomly for you), `rk` (so you don't have to compute it), and `zkproof`.
3. Create Output proofs with `librustzcash_sapling_output_proof`. Give it the witness and it'll output `cv` (again, `rcv` is randomly chosen for you) and the `zkproof`.
4. Once you're ready, run `librustzcash_sapling_binding_sig` to sign for the transaction with the binding key.
5. Finally, sign for all the inputs with `librustzcash_sapling_spend_sig`.
6. Finally finally, free the context with …

Sapling proof API

---

librustzcash/include/librustzcash.h
librustzcash/src/rustzcash.rs

On Windows, the slices are [u16] representing UTF-16. On all other
platforms, the slices are [u8] in the native filesystem encoding.
Closes #44.

Use slices of native strings to pass parameter paths into Rust

---

Cargo.lock
librustzcash/Cargo.toml
librustzcash/src/equihash.rs
librustzcash/src/rustzcash.rs
sapling-crypto/src/circuit/sapling/mod.rs
zcash_primitives/src/transaction/sighash.rs
zcash_proofs/Cargo.toml
zcash_proofs/src/lib.rs
zcash_proofs/src/sapling/mod.rs
zcash_proofs/src/sapling/prover.rs
zcash_proofs/src/sapling/verifier.rs
zip32/src/lib.rs

This PR defines a Rust API (with no `unsafe`) for creating and verifying the Sapling components of a Zcash transaction.

Sapling proving and verifying API

---

bellman/Cargo.toml
bellman/src/lib.rs
bellman/src/multicore.rs

When the `multicore` feature is disabled, an alternate implementation of the multicore operations is used that reduces the parallelization to 1 (preventing sharding of workloads), and immediately blocks on all operations.

Place bellman multicore operations behind a (default) feature flag

---

sapling-crypto/src/circuit/uint32.rs

Use wrapping function to directly disable integer overflow protection.

Closes #52. Fix test error "attempt to shift right with overflow".

---

.travis.yml
Cargo.lock
librustzcash/Cargo.toml
librustzcash/src/equihash.rs
librustzcash/src/rustzcash.rs
sapling-crypto/Cargo.toml
sapling-crypto/src/circuit/blake2s.rs
sapling-crypto/src/circuit/test/mod.rs
sapling-crypto/src/group_hash.rs
sapling-crypto/src/lib.rs
sapling-crypto/src/primitives/mod.rs
sapling-crypto/src/util.rs
zcash_primitives/Cargo.toml
zcash_primitives/src/keys.rs
zcash_primitives/src/lib.rs
zcash_primitives/src/note_encryption.rs
zcash_primitives/src/transaction/sighash.rs
zcash_primitives/src/zip32.rs
zcash_proofs/Cargo.toml
zcash_proofs/src/hashreader.rs
zcash_proofs/src/lib.rs

The primary reason for migrating is that these crates provide APIs for
setting the personalisation string. This enables us to depend solely on
published crates, and thus publish our own crates. (In order for a crate
to be published, it can't depend on unpublished ones.)
The SIMD implementations are ported from libsodium.
Closes #67.

Migrate to blake2b_simd and blake2s_simd crates

---

zcash_primitives/src/zip32.rs

Make some methods in DiversifierIndex and DiversifierKey pub so external wallet generators (like zecpaperwallet) can use them

Make some methods pub for use in External Wallet Generators

---

Cargo.lock
librustzcash/src/rustzcash.rs
zcash_primitives/Cargo.toml
zcash_primitives/src/legacy.rs
zcash_primitives/src/lib.rs
zcash_primitives/src/merkle_tree.rs
zcash_primitives/src/note_encryption.rs
zcash_primitives/src/prover.rs
zcash_primitives/src/sapling.rs
zcash_primitives/src/transaction/builder.rs
zcash_primitives/src/transaction/components.rs
zcash_primitives/src/transaction/components/amount.rs
zcash_primitives/src/transaction/mod.rs
zcash_primitives/src/transaction/sighash.rs
zcash_primitives/src/transaction/tests.rs
zcash_proofs/Cargo.toml
zcash_proofs/src/lib.rs
zcash_proofs/src/prover.rs
zcash_proofs/src/sapling/mod.rs
zcash_proofs/src/sapling/prover.rs
zcash_proofs/src/sapling/verifier.rs

Supports Sapling spends, Sapling outputs, and transparent (P2PKH and P2SH) outputs.

Transaction builder

---

zcash_proofs/src/circuit/pedersen_hash.rs

Currently, `circuit::pedersen_hash::pedersen_hash` always consumes one too many generators because `segment_generators.next()` is called before checking `bits.next()`.

Fix off-by-one so pedersen_hash doesn't consume too many generators.

---

librustzcash/src/rustzcash.rs

This makes the C interface behave like `zcash_proofs` and allows to
init the library without downloading the heavy sprout parameters.
In the special case where `librustzcash_init_zksnark_params` is called
with the sprout arguments path set to NULL and length set to 0, the
arguments are passed as None to `load_parameters`.
Closes #85.

Make initialization of sprout validation key optional

---

.github/workflows/rust.yml
librustzcash/src/rustzcash.rs

librustzcash: Fix typo in Windows parameter init; Correctly map sprout_path. Includes a GitHub actions improvement

---

librustzcash/include/librustzcash.h
librustzcash/src/rustzcash.rs
librustzcash/src/tests/key_agreement.rs
librustzcash/src/tests/key_components.rs
zcash_client_backend/src/encoding.rs
zcash_primitives/src/note_encryption.rs
zcash_primitives/src/primitives.rs
zcash_primitives/src/transaction/builder.rs
zcash_primitives/src/zip32.rs
zcash_proofs/src/circuit/sapling.rs
zcash_proofs/src/sapling/prover.rs

PaymentAddress encapsulation

---

zcash_client_backend/src/keys.rs

This enforces the MUST requirement in ZIP 32. A panic is used instead of
an error because this should be considered an implementation error.
Ideally the type system would prevent this from occurring at all.
Closes #125.

Panic if spending_key is given a seed shorter than 32 bytes

---

librustzcash/Cargo.toml
zcash_primitives/Cargo.toml
zcash_proofs/Cargo.toml

Fixes issue introduced by #134. `rand_core` 0.5.0 does not export `OsRng` in the crate root but 0.5.1 does.
@NikVolf

Specify rand_core >= 0.5.1 for OsRng import.

---

zcash_primitives/src/transaction/mod.rs

Implement PartialOrd and Ord for TxIds, which allows for sorting TxIDs, which is useful for detecting duplicates (~`HashSet` and~ `Vec::dedup` need sorted lists)

Implement sorting for TxIDs

---

Cargo.lock
zcash_client_backend/Cargo.toml
zcash_client_backend/src/welding_rig.rs

Warnings were originally fixed in #134. This warning was introduced in #114, but it wasn't spotted because there was no merge conflict.

Fix rand_os warning in tests

---

.github/workflows/ci.yml
.travis.yml

This should make both coverage generation and Travis CI more reliable (the latter shouldn't time out anymore).

Move code coverage from Travis CI to Actions

---

zcash_primitives/src/transaction/builder.rs

The `sighash` variable was not defined

Compile Fix: Add missing sighash declaration

---

zcash_proofs/Cargo.toml

This enables someone using zcash_proofs to disable multicore.

Pass bellman's multicore feature flag through to zcash_proofs

---

bellman/src/domain.rs
bellman/src/gadgets/num.rs
bellman/src/groth16/generator.rs
bellman/src/groth16/tests/dummy_engine.rs
bellman/src/groth16/tests/mod.rs
ff/ff_derive/src/lib.rs
ff/src/lib.rs
pairing/benches/bls12_381/fq.rs
pairing/benches/bls12_381/fq12.rs
pairing/benches/bls12_381/fq2.rs
pairing/benches/bls12_381/fr.rs
pairing/src/bls12_381/ec.rs
pairing/src/bls12_381/fq.rs
pairing/src/bls12_381/fq12.rs
pairing/src/bls12_381/fq2.rs
pairing/src/bls12_381/fq6.rs
pairing/src/bls12_381/fr.rs
pairing/src/bls12_381/mod.rs
pairing/src/bls12_381/tests/mod.rs
pairing/src/lib.rs
pairing/src/tests/field.rs
zcash_primitives/src/jubjub/edwards.rs
zcash_primitives/src/jubjub/fs.rs
zcash_primitives/src/jubjub/montgomery.rs
zcash_primitives/src/jubjub/tests.rs
zcash_proofs/src/circuit/ecc.rs

The `pairing::bls12_381` and `zcash_primitives::jubjub` implementations are **not** constant-time, but will be replaced by the `bls12_381` and `jubjub` implementations which are.
The `ff_derive` implementation of `sqrt` is constant-time (having been ported from `bls12_381::Scalar`), but the `invert` implementation is **not** constant-time yet.

Constant-time APIs for ff::Field::[invert, sqrt]

---

bellman/src/domain.rs
bellman/src/gadgets/multieq.rs
bellman/src/gadgets/test/mod.rs
bellman/src/groth16/generator.rs
bellman/src/groth16/tests/dummy_engine.rs
bellman/src/groth16/tests/mod.rs
ff/Cargo.toml
ff/ff_derive/src/lib.rs
ff/src/lib.rs
pairing/src/bls12_381/fq.rs
pairing/src/bls12_381/fq2.rs
pairing/src/bls12_381/fr.rs
pairing/src/bls12_381/mod.rs
pairing/src/tests/engine.rs
pairing/src/tests/field.rs
zcash_primitives/src/jubjub/fs.rs

ff::Field::pow_vartime and no_std support

---

.github/workflows/ci.yml

Fixes an issue where cargo-tarpaulin failed to build the crate on 1.37.0, but the crate itself builds fine with that version.

CI: Use stable Rust release for code coverage

---

librustzcash/src/rustzcash.rs
zcash_primitives/src/merkle_tree.rs
zcash_primitives/src/prover.rs
zcash_primitives/src/transaction/builder.rs
zcash_proofs/src/prover.rs
zcash_proofs/src/sapling/prover.rs

Most of this is much-needed refactoring, but there are a few small usability improvements:
- `Builder::add_sapling_spend` now takes a `MerklePath` directly, thanks to the newly-added `MerklePath::root(leaf: Node)`.
- `Builder::build` now takes `impl TxProver` by reference, so the caller may reuse it.

UX refactors for proving-related APIs

---

zcash_primitives/src/transaction/builder.rs

Add binding signature only if needed

---

zcash_proofs/src/lib.rs
zcash_proofs/src/prover.rs

Define the spend_hash and output_hash circuit hashes as constants in the load_parameters function, so we don't have to take them as function arguments.
Closes #106

Hard-code Sapling circuit hashes in zcash_proofs crate

---

bellman/src/domain.rs
bellman/src/groth16/generator.rs
bellman/src/groth16/mod.rs
bellman/src/groth16/prover.rs
bellman/src/groth16/tests/dummy_engine.rs
bellman/src/multiexp.rs
ff/ff_derive/src/lib.rs
ff/src/lib.rs
group/Cargo.toml
group/src/lib.rs
group/src/tests/mod.rs
group/src/wnaf.rs
pairing/benches/bls12_381/ec.rs
pairing/benches/bls12_381/mod.rs
pairing/src/bls12_381/ec.rs
pairing/src/bls12_381/fq12.rs
pairing/src/bls12_381/fq2.rs
pairing/src/bls12_381/fq6.rs
pairing/src/bls12_381/mod.rs
pairing/src/bls12_381/tests/mod.rs
pairing/src/lib.rs
pairing/src/tests/engine.rs
zcash_primitives/src/jubjub/fs.rs

The new `Group` trait represents a cryptographic group with a large prime-order subgroup and a small cofactor. The `PrimeGroup` trait further constrains the group to have a cofactor of one. `CurveProjective` now primarily contains EC-specific functionality.
Part of #161.

group crate refactoring

---

bellman/src/lib.rs
bls12_381/src/notes/design.rs
pairing/src/bls12_381/ec.rs
zcash_client_backend/Cargo.toml
zcash_client_backend/build.rs
zcash_primitives/src/lib.rs
zcash_primitives/src/note_encryption.rs
zcash_primitives/src/transaction/components.rs

Addresses lints that are [visible when checking with nightly](https://github.com/zcash/librustzcash/pull/205/files) (rather than the current MSRV of 1.39).

Lint fixes

---

zcash_primitives/src/transaction/components.rs

Zecwallet Lite currently depends on a fork of `librustzcash`, which has some minor additions to the upstream `librustzcash`. It would be awesome if `librustzcash` added these changes, so I can depend directly on `librustzcash`.

Expose the `hash` and `n` fields of Transparent Outputs

---

bellman/src/domain.rs
bellman/src/groth16/generator.rs
bellman/src/groth16/mod.rs
bellman/src/groth16/prover.rs
bellman/src/groth16/tests/dummy_engine.rs
bellman/src/groth16/verifier.rs
bellman/src/multiexp.rs
ff/src/lib.rs
group/src/cofactor.rs
group/src/lib.rs
group/src/prime.rs
group/src/tests/mod.rs
group/src/wnaf.rs
pairing/src/bls12_381/ec.rs
pairing/src/bls12_381/mod.rs
pairing/src/bls12_381/tests/mod.rs
pairing/src/lib.rs
pairing/src/tests/engine.rs

This implements the current version of https://github.com/zkcrypto/group/issues/6, and provides APIs that we can implement for the `bls12_381` and `jubjub` crates.
Closes #161.

New group traits

---

bls12_381/Cargo.toml
bls12_381/src/fp.rs
bls12_381/src/scalar.rs
jubjub/Cargo.toml
jubjub/src/fr.rs

Implement ff traits for bls12_381 and jubjub crates

---

zcash_proofs/Cargo.toml
zcash_proofs/src/lib.rs
zcash_proofs/src/prover.rs

Requires the `bundled-prover` feature for the `zcash_proofs` crate, which enables the `wagyu-zcash-parameters` crate and adds around 50 MiB to the overall binary size. That crate bundles the same Sapling parameter files we normally obtain from disk, so we constrain them to match the same hard-coded hashes.

zcash_proofs: Add LocalProver::bundled

---

bellman/src/groth16/mod.rs
bellman/src/groth16/tests/mod.rs
bellman/src/groth16/verifier.rs
bellman/src/lib.rs
bellman/tests/mimc.rs
zcash_proofs/src/sapling/prover.rs
zcash_proofs/src/sapling/verifier.rs
zcash_proofs/src/sprout.rs

This adds a distinct VerificationError type to the crate and changes
`verify_proof` to return `Result<(), VerificationError>` rather than
`Result<bool, SynthesisError>`.  This is significantly safer, because it avoids
the need to mix pattern-matching logic with boolean logic (the cause of
RUSTSEC-2019-0004).

bellman: add VerificationError

---

.github/workflows/ci.yml

This ensures that we don't introduce any regressions for WASM consumers.
Closes zcash/zcash#4655.

CI: Build zcash_proofs against WASM targets

---

zcash_client_backend/src/decrypt.rs
zcash_client_backend/src/lib.rs
zcash_client_backend/src/welding_rig.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/scan.rs
zcash_client_sqlite/src/transact.rs
zcash_primitives/src/consensus.rs
zcash_primitives/src/lib.rs
zcash_primitives/src/note_encryption.rs
zcash_primitives/src/primitives.rs
zcash_primitives/src/prover.rs
zcash_primitives/src/transaction/builder.rs
zcash_primitives/src/util.rs
zcash_proofs/src/circuit/sapling.rs
zcash_proofs/src/prover.rs
zcash_proofs/src/sapling/prover.rs

Closes https://github.com/zcash/librustzcash/issues/260

ZIP212 implementation

---

bellman/src/groth16/generator.rs
bellman/src/groth16/mod.rs
bellman/src/groth16/prover.rs
bellman/src/groth16/tests/dummy_engine.rs
bellman/src/groth16/verifier.rs
bellman/src/multiexp.rs
bls12_381/src/fp.rs
bls12_381/src/fp2.rs
bls12_381/src/scalar.rs
group/src/tests/mod.rs
jubjub/src/fr.rs
jubjub/src/lib.rs
pairing/src/bls12_381/ec.rs
pairing/src/bls12_381/mod.rs
pairing/src/bls12_381/tests/mod.rs
pairing/src/lib.rs
pairing/src/tests/engine.rs

- `pairing::Engine` now requires G1 and G2 to be prime-order groups.
- We no longer use `Choice::unwrap_u8`.

Refactor fixes

---

zcash_primitives/src/note_encryption.rs

This PR slightly modifies the sapling recovery functionality to give users of this library the ability to decrypt a sapling output given they only have their `ock`, instead of the `ovk`.
`prf_ock` is also changed to public, to allow library users the ability to generate an ock for later usage.

Decrypt sapling output description given OCK 

---

bls12_381/Cargo.toml
bls12_381/src/fp.rs
bls12_381/src/fp12.rs
bls12_381/src/fp2.rs
bls12_381/src/fp6.rs
bls12_381/src/g1.rs
bls12_381/src/g2.rs
bls12_381/src/lib.rs
bls12_381/src/pairings.rs
group/src/lib.rs
jubjub/Cargo.toml
jubjub/src/lib.rs

Closes #163. Closes #167. Closes #169.

Implement group and pairing traits for bls12_381 and jubjub crates

---

zcash_client_backend/src/welding_rig.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/transact.rs
zcash_primitives/src/note_encryption.rs
zcash_primitives/src/transaction/builder.rs

zcash_primitives: Support ovk = ⊥ in note encryption

---

zcash_client_backend/Cargo.toml
zcash_client_sqlite/Cargo.toml
zcash_primitives/Cargo.toml
zcash_proofs/Cargo.toml

Bumps zcash_proofs, zcash_primitives, zcash_client_backend to 0.4.0
Also bumps zcash_client_sqlite to 0.2.0

Version bump 0.4.0 for crates

---

zcash_proofs/src/constants.rs
zcash_proofs/src/lib.rs

To be able to use the `ecc::fixed_base_multiplication` (which is publicly exposed in the API), you need to be able to access these constants and potentially generate your own.

Make fixed generator functions publicly accessible

---

zcash_primitives/benches/note_decryption.rs

zcash/librustzcash#290 added a benchmark that relied on an API that was
altered by zcash/librustzcash#261, but the PRs didn't cause merge
conflicts, so the issue was only noticed once both had been merged.

zcash_primitives: Fix note decryption benchmarks

---

zcash_primitives/src/legacy.rs

Improves readability, and makes it clearer that we are splitting the output scripts into three subslices.

zcash_primitives: Small simplification to Script::address

---

zcash_client_backend/build.rs
zcash_history/examples/lib/shared.rs
zcash_history/examples/long.rs
zcash_history/src/tree.rs
zcash_primitives/src/block.rs
zcash_primitives/src/constants.rs
zcash_primitives/src/keys.rs
zcash_primitives/src/merkle_tree.rs
zcash_primitives/src/note_encryption.rs
zcash_primitives/src/pedersen_hash.rs
zcash_primitives/src/primitives.rs
zcash_primitives/src/redjubjub.rs
zcash_primitives/src/serialize.rs
zcash_primitives/src/transaction/builder.rs
zcash_primitives/src/transaction/components.rs
zcash_primitives/src/transaction/components/amount.rs
zcash_primitives/src/transaction/mod.rs
zcash_primitives/src/transaction/tests.rs
zcash_primitives/src/util.rs
zcash_primitives/src/zip32.rs
zcash_proofs/src/circuit/ecc.rs
zcash_proofs/src/circuit/sprout/input.rs
zcash_proofs/src/constants.rs
zcash_proofs/src/lib.rs
zcash_proofs/src/sapling/prover.rs
zcash_proofs/src/sapling/verifier.rs

This doesn't clean everything; in particular, I've ignored `zcash_client_backend` and `zcash_client_sqlite` to avoid creating annoying conflicts with #307 (which already needs to be rebased after the bugfix in #311 was merged).

Remove a bunch of lint

---

.github/workflows/ci.yml
zcash_primitives/src/transaction/sighash.rs

When implementing transaction nonmalleability, it will be useful
to have this already done.

Make the functions which produce the components of the sighash reusable.

---

zcash_extensions/Cargo.toml
zcash_primitives/Cargo.toml
zcash_primitives/src/consensus.rs
zcash_primitives/src/lib.rs
zcash_primitives/src/transaction/builder.rs
zcash_primitives/src/transaction/components.rs
zcash_primitives/src/transaction/mod.rs
zcash_primitives/src/transaction/sighash.rs
zcash_primitives/src/transaction/tests.rs

This also uses the test-dependencies feature flag for conditional
inclusion of proptest-related modules which may be used by
dependent crates for generation of samples in testing.

Use rust feature flagging to allow conditionally enabling TZE-related code.

---

zcash_client_backend/Cargo.toml
zcash_client_backend/examples/diversify-address.rs

Usage:
```
cargo run --example diversify-address -- SAPLING_VIEWING_KEY [DIVERSIFIER_INDEX]
```
If `DIVERSIFIER_INDEX` is not specified, it defaults to zero (which generates the default diversified address).
As not all diversifier indices correspond to a valid Sapling address, the binary starts looking from the given index, and returns the first valid Sapling address it can find, along with its corresponding diversifier index.

zcash_client_backend: Add example to generate diversified addresses

---

zcash_client_backend/examples/diversify-address.rs

I misunderstood the meanings of `Err(_)` vs `Ok(None)`, which indicates that
we need to refactor this API! In the meantime, this enables the example
to work with testnet Sapling viewing keys.

zcash_client_backend: Fix testnet bug in diversify-address example

---

zcash_primitives/src/note_encryption.rs

```
Sapling note decryption/valid                                                                            
time:   [581.10 us 582.21 us 583.60 us]
change: [-7.7891% -7.3391% -6.7990%] (p = 0.00 < 0.05)
Performance has improved.
Found 8 outliers among 100 measurements (8.00%)
3 (3.00%) high mild
5 (5.00%) high severe
Sapling note decryption/invalid                                                                            
time:   [84.959 us 85.175 us 85.431 us]
change: [-31.862% -31.399% -30.921%] (p = 0.00 < 0.05)
Performance has improved.
Found 2 outliers among 100 measurements (2.00%)
2 (2.00%) high mild
```

Use wNAF multiplication for Sapling key agreement.

---

components/equihash/CHANGELOG.md
zcash_client_backend/CHANGELOG.md
zcash_client_sqlite/CHANGELOG.md
zcash_extensions/CHANGELOG.md
zcash_history/CHANGELOG.md
zcash_primitives/CHANGELOG.md
zcash_proofs/CHANGELOG.md

The changelogs are accurate for the 0.4.0 release tag, but don't yet
include changes before or after that tag.

Add changelogs to the crates

---

zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/chain.rs
zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/wallet.rs
zcash_client_backend/src/welding_rig.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet.rs
zcash_primitives/src/merkle_tree.rs
zcash_primitives/src/primitives.rs

This removes the `WalletWrite::transactionally` method to make this interface implementable for back-ends that do not support transactionality (such as FFI or network calls). The `WalletWrite` trait is also simplified so as not to tie wallet backends to using the same data representation as the SQLite backend.
Careful review is requested to ensure that incremental witness update semantics are correctly preserved by this refactoring.

Make data access API write calls atomic.

---

zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/welding_rig.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/transact.rs

zcash_client_backend: Use correct output index for t-addr recipients

---

zcash_client_backend/src/zip321.rs

This also adds documentation for the zip321 module.

Update ZIP 321 parsing to use the MemoBytes type.

---

Cargo.toml
components/zcash_note_encryption/Cargo.toml
components/zcash_note_encryption/src/lib.rs

The general note encryption logic shared between Sapling and Orchard will be moved into here.

Empty zcash_note_encryption crate

---

zcash_primitives/src/sapling.rs

The code in jubjub crate for random() seems to be doing the exact same as this code section. Ran cargo test and everything seems fine.

Replace redundant code with call to Field::random() which does the same as the code.

---

zcash_primitives/src/transaction/builder.rs

When computing large transactions that have several notes or spends, it can take several seconds or minutes for the transaction to compute. Wallets should show progress during this long running computation. 
This PR is a proposal to add a notifier channel to the builder, so callers can watch the progress of building a transaction and report it to the user. 
See also: https://github.com/zcash/librustzcash/issues/376

Report Sapling Tx Builder Progress

---

zcash_primitives/CHANGELOG.md
zcash_primitives/src/transaction/builder.rs

This is what builder methods are for :) and it helps to limit the growth of alternate `build` methods.

Builder: Move progress notifier configuration to a builder method

---

components/zcash_note_encryption/src/lib.rs
zcash_client_backend/Cargo.toml
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/error.rs
zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/proto.rs
zcash_client_backend/src/welding_rig.rs
zcash_client_sqlite/src/chain.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/transact.rs
zcash_extensions/src/transparent/demo.rs
zcash_primitives/CHANGELOG.md
zcash_primitives/Cargo.toml
zcash_primitives/src/consensus.rs
zcash_primitives/src/sapling.rs
zcash_primitives/src/transaction/builder.rs
zcash_primitives/src/transaction/components/amount.rs
zcash_primitives/src/transaction/components/tze.rs
zcash_primitives/src/transaction/mod.rs
zcash_primitives/src/zip32.rs

This is a set of minor improvements to type safety factored out from #375.

ZIP-225/244 #1: Minor refactoring and preparatory updates.

---

zcash_client_backend/src/data_api/wallet.rs
zcash_extensions/src/transparent/demo.rs
zcash_primitives/CHANGELOG.md
zcash_primitives/src/transaction/builder.rs
zcash_primitives/src/transaction/components/amount.rs
zcash_primitives/src/transaction/components/sapling.rs
zcash_primitives/src/transaction/components/sapling/builder.rs
zcash_primitives/src/transaction/components/transparent.rs
zcash_primitives/src/transaction/components/transparent/builder.rs
zcash_primitives/src/transaction/components/tze.rs
zcash_primitives/src/transaction/components/tze/builder.rs
zcash_primitives/src/transaction/mod.rs

This extends from #385 as refactoring prior to ZIP-225 implementation.

ZIP-225/244 #2: Refactor transaction builder to create separate builders for each section.

---

Cargo.toml
components/zcash_note_encryption/Cargo.toml
zcash_client_backend/Cargo.toml
zcash_client_sqlite/Cargo.toml
zcash_extensions/Cargo.toml
zcash_primitives/Cargo.toml
zcash_proofs/Cargo.toml
zcash_proofs/src/circuit/ecc.rs
zcash_proofs/src/circuit/sapling.rs

Requires patching two dependencies:
- nom is part of the funty breakage; we are blocking on a new release.
- orchard is in development.

Migrate to bitvec 0.22, ff 0.10, etc.

---

zcash_primitives/CHANGELOG.md
zcash_primitives/src/sapling/redjubjub.rs
zcash_proofs/CHANGELOG.md
zcash_proofs/src/sapling/verifier.rs

`PublicKey::verify` now always uses post-ZIP 216 validation rules, which
is fine in non-consensus contexts.
`SaplingVerificationContext` is used by `zcashd`'s consensus rules.
Closes zcash/librustzcash#394.

Impl ZIP 216 on SaplingVerificationContext and redjubjub::PublicKey

---

components/zcash_note_encryption/src/lib.rs
zcash_primitives/src/sapling/note_encryption.rs
zcash_primitives/src/transaction/components/sapling.rs

This replaces the `ShieldedOutput::epk() -> &Domain::EphemeralPublicKey` which could not be satisfied by output types that did not parse epk.

zcash_note_encryption: Add `ShieldedOutput::ephemeral_key() -> EphemeralKeyBytes`

---

zcash_primitives/src/transaction/components/amount.rs

This is necessary in order to be able to calculate bvk for Orchard bundles.

impl From<Amount> for orchard::ValueSum

---

zcash_history/CHANGELOG.md
zcash_history/examples/lib/shared.rs
zcash_history/examples/long.rs
zcash_history/src/entry.rs
zcash_history/src/lib.rs
zcash_history/src/node_data.rs
zcash_history/src/tree.rs
zcash_history/src/version.rs

We add support for multiple history tree versions with a marker trait, and add marker structs for the two currently-defined history tree versions.
Closes zcash/librustzcash#368.

`zcash_history`: Implement v2 history tree with Orchard support

---

Cargo.toml
zcash_primitives/src/transaction/components/orchard.rs

Includes additional patched dependencies, now that the orchard crate is not pinning specific revisions of the in-development crates.

Bump orchard deps

---

components/equihash/Cargo.toml
components/zcash_address/Cargo.toml
components/zcash_note_encryption/Cargo.toml
zcash_client_backend/Cargo.toml
zcash_client_sqlite/Cargo.toml
zcash_extensions/Cargo.toml
zcash_history/Cargo.toml
zcash_primitives/Cargo.toml
zcash_primitives/benches/note_decryption.rs
zcash_primitives/benches/pedersen_hash.rs
zcash_proofs/Cargo.toml

These are effectively identical to full-output trial decryption (as the
primary cost is the scalar multiplication), but it's good to check.
This PR also now enables flamegraph profiling of the `zcash_primitives` benchmarks.

zcash_primitives: Benchmark trial decryption of compact outputs

---

components/zcash_note_encryption/src/lib.rs
zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/proto.rs
zcash_client_backend/src/wallet.rs
zcash_client_backend/src/welding_rig.rs
zcash_primitives/CHANGELOG.md
zcash_primitives/benches/note_decryption.rs
zcash_primitives/src/sapling/note_encryption.rs
zcash_primitives/src/transaction/components/sapling.rs
zcash_primitives/src/transaction/components/sapling/builder.rs
zcash_primitives/src/transaction/txid.rs

This removes an unnecessary `to_bytes` during trial decryption of notes,
and more closely matches the protocol spec. We retain the consensus rule
canonicity check on epk due to `SaplingVerificationContext::check_output`
taking a `jubjub::ExtendedPoint`, forcing `zcashd` to parse the bytes.

Store OutputDescription `ephemeral_key` as bytes

---

Cargo.toml
components/zcash_address/Cargo.toml
zcash_client_backend/Cargo.toml
zcash_primitives/Cargo.toml

This bumps everything that isn't a patched dependency, except:
- `rusqlite` (we should merge #341 first).
- `quickcheck` (the `1.0` is painful, we should switch to `proptest` instead like everything else).

Bump dependencies

---

.github/dependabot.yml

This will be easier than remembering to update them manually.

CI: Add Dependabot config to keep GitHub Actions up-to-date

---

Cargo.toml
components/zcash_note_encryption/src/batch.rs
components/zcash_note_encryption/src/lib.rs
zcash_primitives/src/sapling/note_encryption.rs

This change makes it possible to make the crate no-std compatible.

Introduce `zcash_note_encryption::BatchDomain` trait

---

components/zcash_note_encryption/Cargo.toml
components/zcash_note_encryption/src/batch.rs
components/zcash_note_encryption/src/lib.rs

This PR adds no_std compatibility for zcash_note_encryption.
All functionalities and API are preserved. Modifications are light and straightforward.
Motivation: implementation into Trezor and other hardware wallets.

Add `#![no_std]` support for zcash_note_encryption

---

zcash_primitives/src/zip32.rs

Given a diversifier key, decrypts a diversifier to obtain
the diversifier index from which the diversifier was originally
produced.

Add decryption of Sapling diversifiers.

---

components/zcash_address/Cargo.toml
components/zcash_encoding/Cargo.toml
zcash_extensions/Cargo.toml
zcash_primitives/Cargo.toml

Some references to deps that look like they were not needed. 
(tool: undepend)

Removing unused deps

---

zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/keys.rs
zcash_client_backend/src/wallet.rs
zcash_client_sqlite/Cargo.toml
zcash_primitives/Cargo.toml
zcash_primitives/src/lib.rs
zcash_primitives/src/transparent.rs
zcash_primitives/src/zip32.rs

Implements ZIP 316 changes as specified in https://github.com/zcash/zips/pull/576/.
This is based on the autoshielding branch https://github.com/nuttycom/librustzcash/tree/autoshield-poc-daa, i.e. on top of #341.

[ZIP 316] Transparent internal and external ovk

---

zcash_client_backend/Cargo.toml
zcash_client_sqlite/Cargo.toml

`protobuf 2.26.0` bumped its MSRV to 1.52.1, which is incompatible with
our current MSRV.

Restrict cargo to `protobuf >=2.20,<2.26`

---

components/f4jumble/src/lib.rs
components/zcash_address/src/kind/unified.rs

Following on from the work to make `f4jumble` no-std compatible.

`zcash_address` cleanups

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/proto/compact_formats.proto
zcash_client_backend/src/proto.rs
zcash_client_backend/src/welding_rig.rs
zcash_client_sqlite/src/lib.rs

Source: https://github.com/zcash/lightwalletd/blob/83bb19918fb36a5f6d5013fba7938daf3d73db1d/walletrpc/compact_formats.proto

zcash_client_backend: Bring in latest `compact_formats.proto`

---

zcash_primitives/src/consensus.rs

The previous version of this pull request was made from a fork, rather than from the main zcash/librustzcash repository. This commit needs to be referenced directly by https://github.com/zcash/zcash/pull/5868; this PR should not be merged until after that PR's contents have been merged to the `master` branch and zcashd v4.7.0 has been released.

Set NU5 testnet reactivation height.

---

zcash_history/Cargo.toml
zcash_history/src/node_data.rs

`bigint`'s deprecation message suggests to use `uint` instead.
`uint`'s documentation suggests using `primitive-types` for
128 and 256 bit unsigned integers; these use `uint` under the
hood but do provide a somewhat more complete (and hopefully stable)
API.
Fixes #527

Replace the deprecated `bigint` crate with `primitive-types`.

---

components/zcash_address/src/lib.rs

This provides the encoding corresponding to
`ZcashAddress::try_from_encoded` and documents the fact that the
`Display` instance can also provide this encoding.
Fixes #463

Add `ZcashAddress::encode` method.

---

zcash_primitives/src/lib.rs
zcash_primitives/src/merkle_tree.rs

Allow CommitmentTree completeness & auth paths to be computed at arbitrary depths.

---

components/f4jumble/CHANGELOG.md
components/f4jumble/Cargo.toml
components/zcash_address/CHANGELOG.md
components/zcash_address/Cargo.toml
components/zcash_encoding/CHANGELOG.md
components/zcash_encoding/Cargo.toml
components/zcash_note_encryption/Cargo.toml
zcash_client_backend/Cargo.toml
zcash_client_sqlite/Cargo.toml
zcash_extensions/Cargo.toml
zcash_history/CHANGELOG.md
zcash_history/Cargo.toml
zcash_primitives/CHANGELOG.md
zcash_primitives/Cargo.toml
zcash_proofs/CHANGELOG.md
zcash_proofs/Cargo.toml

Release `zcash_primitives 0.6.0` et al

---

zcash_primitives/src/consensus.rs

This enables mobile wallets using versions of the mobile SDKs based on zcash/librustzcash@8e3e7de50c3c35bd7c18988bb629dd1baeb1a3d1 to send transactions after NU5 activation. These wallets will however still not support receiving v5 transactions.

Backport NU5 branch ID and activation heights for mobile SDKs

---

components/zcash_address/CHANGELOG.md
components/zcash_address/src/convert.rs
components/zcash_address/src/lib.rs

This enables the user-defined conversions to be fallible, which they will almost always want to be (as address data needs to be validated before it can be used).
Closes zcash/librustzcash#563.

zcash_address: Replace `FromAddress` with `TryFromAddress`

---

zcash_proofs/Cargo.toml
zcash_proofs/examples/download-params.rs
zcash_proofs/examples/download-sprout-and-sapling-params.rs
zcash_proofs/src/downloadreader.rs
zcash_proofs/src/hashreader.rs
zcash_proofs/src/lib.rs

Zebra wants to use `zcash_proofs` to download both Sprout and Sapling parameters.
Add sprout:
- Add a `download_sprout_parameters` function.
- Stream sprout and sapling downloads to disk, rather than loading the whole file into RAM.
Functionality changes:
- If the parameter files already exist, check them instead of starting a download.
- Allow the caller to specify a download timeout.
- Check file sizes as well as file hashes (useful for debugging).
- Remove downloaded files on error (but leave existing files alone) .
Interface changes:
- Add `download_sapling_parameters` and deprecate `download_parameters`. This avoids confusion between sprout and sapling downloads, while maintaining backward compatibility.
- Make the Sprout and Sapling parameter file names public. This makes it easier …

Download sprout parameters in zcash_proofs

---

Cargo.toml
zcash_client_backend/CHANGELOG.md
zcash_client_backend/examples/diversify-address.rs
zcash_client_backend/src/encoding.rs
zcash_client_backend/src/zip321.rs
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/Cargo.toml
zcash_client_sqlite/src/chain.rs
zcash_client_sqlite/src/error.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/transact.rs
zcash_primitives/src/sapling/keys.rs

This change adds database migration infrastructure to zcash_client_sqlite,
and replaces wallet database initialization with running database migrations.
The migrations introduced by this change should be able to safely upgrade 
wallet databases based on `librustzcash` versions 0.3.0 and also any databases
that have already applied the changes to wallet initialization expected by the
09f4d90a32434462fcd37e9f843cb015cf313fa7 lineage of commits.

Add database migrations to zcash_client_sqlite.

---

zcash_client_backend/src/data_api/error.rs
zcash_client_backend/src/data_api/wallet.rs
zcash_primitives/CHANGELOG.md
zcash_primitives/src/sapling/keys.rs

This updates `shield_transparent_funds` to look up the internal
(change) address for the account specified, and use that as the
destination for shielding transparent funds.

Shield funds to the internal Sapling key for a specified account.

---

zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/prepared.rs
zcash_client_sqlite/src/wallet.rs

This PR is overall a no-op, but collects all usages of `DataConnStmtCache` prepared statements into a private submodule `zcash_client_sqlite::prepared`. This forces the rest of the crate to only interact with the statements through type-safe APIs, and keeps the definition and execution of prepared statements close together for reviewability.

`zcash_client_sqlite`: Improve type safety for prepared statements

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/Cargo.toml
zcash_client_backend/src/data_api.rs
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/Cargo.toml
zcash_client_sqlite/src/error.rs
zcash_client_sqlite/src/lib.rs

This is to replace the database mutations in the Android SDK. It is placed behind an `unstable` feature flag until we are satisfied that it is suitable as a general-purpose API (or replace it).

zcash_client_backend: Add `WalletWrite::remove_unmined_tx` method

---

zcash_primitives/src/zip32.rs

This implementation is copied from https://github.com/zcash/zcash/blob/master/src/zcash/address/zip32.h#L84-L93

Add conversions from u32 and u64 to DiversifierIndex

---

zcash_primitives/src/sapling.rs

The `zcashd` Rust code relies on being able to construct the Sapling
types transparently. This part of the "public API" of the crate was
broken when the `NullifierDerivingKey` newtype was introduced. We do
want to migrate to all of these types having stronger type safety
guarantees (by only constructing them via constructors), but that should
be done consistently across the types. For now we maintain the existing
API by changing `NullifierDerivingKey` to be a transparent newtype.

zcash_primitives: Make `NullifierDerivingKey` internals public

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/src/error.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/prepared.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/init/migrations/addresses_table.rs

This updates the data access API to provide diversified address functionality. In order to support this change, the addresses table is updated to store diversifier index information in big-endian order to allow sorting by diversifier index, and account initialization is updated to store the diversifier index accordingly. The currently unreleased `addresses_table` migration is updated to reflect this change.

Replace `get_address` with `get_current_address` and `get_next_available_address`

---

zcash_client_backend/src/data_api/chain.rs
zcash_client_backend/src/scan.rs
zcash_client_backend/src/welding_rig.rs
zcash_primitives/src/sapling/keys.rs

This removes the dependency on `SaplingIvk::to_repr()`, and enables us to alter the type of `D::IncomingViewingKey` to improve the performance of batch scanning.
For the welding rig, we already annotate the viewing keys with `AccountId`, so we use `(AccountId, Scope)` as the tag.

zcash_client_backend: Add tags to IVKs in the batch scanner

---

.github/workflows/ci.yml

This deploys https://github.com/xd009642/tarpaulin/pull/940 for (hopefully) improved coverage information.

CI: Migrate to `cargo-tarpaulin` branch with LLVM source coverage engine

---

zcash_primitives/Cargo.toml
zcash_primitives/src/sapling/note_encryption.rs

This makes it consistent with zcash_note_encryption. fixes #650

Update chacha20poly1305 dependency in zcash_primitives to 0.10

---

Cargo.toml
zcash_client_backend/src/data_api/chain.rs
zcash_client_backend/src/scan.rs
zcash_client_backend/src/welding_rig.rs
zcash_primitives/CHANGELOG.md
zcash_primitives/Cargo.toml
zcash_primitives/src/block.rs
zcash_primitives/src/consensus.rs
zcash_primitives/src/sapling/keys.rs
zcash_primitives/src/sapling/note_encryption.rs
zcash_primitives/src/transaction/components/amount.rs
zcash_primitives/src/transaction/components/sapling.rs
zcash_primitives/src/transaction/mod.rs
zcash_primitives/src/zip32.rs

The new approach now correctly measures the heap usage of the precomputed IVKs used for Sapling as of #633. It also fixes several bugs that resulted in undercounting.
Depends on https://github.com/zkcrypto/group/pull/37.

`zcash_client_backend`: Refactor tracking of `BatchRunner` heap memory usage

---

zcash_client_sqlite/src/wallet.rs

This had the same bug as was fixed in 5b8ec380a006ccc0ccb38c11cc6832e1176015c0

zcash_client_sqlite: fix wallet::get_max_account_id

---

zcash_proofs/src/downloadreader.rs
zcash_proofs/src/lib.rs

The implementation of `io:Read` for `ResponseLazyReader` used to return
only one byte regardless of the size of the provided `buf`, which
degraded the performance of loading the response.
This change makes use of the provided `buf`. On my machine with Rust
1.64, the downloading speed went up from ~100 KiB/s to ~2 MiB/s.
However, as before this change, the process still uses 100% of a single
CPU thread when downloading the response. The most likely reason is that
we still manually read each byte of the response. I can download the
same data with ~ 50 MiB/s on my machine using a different HTTP client.
This fix seems to be sufficient for now.

zcash_proofs: Temporarily fix params download

---

zcash_client_backend/src/wallet.rs
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/prepared.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/init/migrations.rs
zcash_client_sqlite/src/wallet/init/migrations/add_transaction_views.rs
zcash_client_sqlite/src/wallet/init/migrations/add_utxo_account.rs

The ios FFI was still relying upon a deprecated approach to handling transparent UTXOs, deleting
all of them above a certain height and repopulating them each time they were retrieved. Now, instead,
the `put_received_transparent_utxo` data access API method actually performs a proper upsert, so
there should be no need for the clear function.
This builds on #656

Use upsert functionality for transparent UTXOs, rather than delete/repopulate.

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/decrypt.rs
zcash_client_backend/src/encoding.rs
zcash_client_backend/src/lib.rs
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/prepared.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/init/migrations.rs
zcash_client_sqlite/src/wallet/init/migrations/sent_notes_to_internal.rs
zcash_client_sqlite/src/wallet/init/migrations/ufvk_support.rs

This adds trial decryption with the internal IVK and correctly tracks payments sent to the wallet-internal address in the wallet database.

Track inputs sent to wallet-internal recipients

---

zcash_client_backend/src/wallet.rs
zcash_client_sqlite/src/prepared.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/init/migrations/addresses_table.rs

Due to how the wallets retrieved unspent transparent outputs from the light wallet server, the account associated with a particular UTXO may not be known by the light wallet. Instead of requiring the caller to perform a separate lookup and match the address of the received UTXO with a known account, it's simpler to perform this lookup internally at the time of insertion or update.
In order to make this operation more efficient, the `addresses_table` migration is modified to add a column containing the transparent receiver so that they may be used in the joins in the UTXO insert and update operations.

Remove `received_by_account` field from WalletTransparentOutput

---

components/f4jumble/Cargo.toml
components/zcash_note_encryption/Cargo.toml
zcash_client_backend/Cargo.toml
zcash_client_sqlite/Cargo.toml

These were mostly detected with `cargo-udeps`, for which I've also added exclusions for the dependencies it can't detect are used in doc-tests.

Remove unused dependencies

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/error.rs
zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/wallet.rs
zcash_client_sqlite/src/lib.rs

These traits introduce a problem, in that constraints on a method cannot be conditionally required based upon the presence or absence of a feature flag. Instead, we make the methods previously introduced by the removed traits present in all cases on the `WalletRead` and `WalletWrite` traits, but ensure that their implementations return an error if the caller attempts to use them in a wallet that has not been configured with support for transparent inputs functionality.

Remove the `WalletReadTransparent` and `WalletWriteTransparent` extension traits.

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/wallet.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/prepared.rs
zcash_client_sqlite/src/wallet.rs
zcash_primitives/CHANGELOG.md
zcash_primitives/src/legacy.rs
zcash_primitives/src/transaction/components/transparent.rs

This modifies `decrypt_and_store_transaction` to check for inputs
to a transaction being decrypted that correspond to addresses in
our wallet. For each such UTXO found, it is marked spent in our
`utxos` table if present.

Mark our utxos spent when we detect them as inputs to a transaction.

---

zcash_client_backend/src/data_api/wallet.rs

In 47a0d0d2b789c816525aa1d07c0ebbfd67758cf1 `WalletWriteTransparent` was merged into `WalletWrite`, including its associated type `UtxoRef`. However, `shield_transparent_funds` placed a bound on this associated type that was not moved to `WalletWrite`. This left the generic parameter `U` unconstrained, which didn't cause a local failure because the method has no local tests, but was immediately apparent when trying to use the method in the mobile SDKs.

zcash_client_backend: Fix missing bound

---

Cargo.toml
zcash_client_backend/CHANGELOG.md
zcash_client_backend/Cargo.toml
zcash_client_backend/build.rs
zcash_client_backend/src/keys.rs
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/Cargo.toml
zcash_client_sqlite/src/prepared.rs
zcash_client_sqlite/src/wallet/init.rs
zcash_extensions/Cargo.toml
zcash_primitives/CHANGELOG.md
zcash_primitives/Cargo.toml
zcash_primitives/src/legacy.rs
zcash_primitives/src/transaction/components/transparent/builder.rs
zcash_primitives/src/transaction/util/sha256d.rs
zcash_proofs/CHANGELOG.md
zcash_proofs/Cargo.toml
zcash_proofs/src/lib.rs
zcash_proofs/src/sprout.rs

* This updates the `zcash_primitives` crate to use `orchard 0.3` which is a breaking change; we do a release of `zcash_primitives 0.8`.
* We update `zcash_proofs` to use `zcash_primitives 0.8` which is a breaking change; we do a release of `zcash_proofs 0.8`.
* We update `zcash_extensions`, `zcash_client_backend`, `zcash_client_sqlite` to use `zcash_primitives 0.8` which is a breaking change; we are not releasing these crates in this PR.
* We also update `zcash_client_backend` to use `orchard 0.3`.

Update zcash_primitives to orchard 0.3; release zcash_primitives and zcash_proofs 0.8.

---

zcash_history/CHANGELOG.md

The MSRV bump was actually in `zcash_history` 0.3.0, even though the addition of that to the Cargo.toml file was post-0.3.0 release.

This reverts a previous incorrect change to the changelog.

---

components/zcash_address/CHANGELOG.md
components/zcash_address/Cargo.toml
components/zcash_encoding/CHANGELOG.md
components/zcash_encoding/Cargo.toml
zcash_client_backend/Cargo.toml
zcash_client_sqlite/Cargo.toml
zcash_extensions/Cargo.toml
zcash_primitives/CHANGELOG.md
zcash_primitives/Cargo.toml

This bumps `zcash_address` and `zcash_encoding` versions to 0.2. Then, it bumps `zcash_primitives` to `0.8.1` (which now depend on the new versions of `zcash_address` and `zcash_encoding`) with the goal to yank `0.8.0` which was mistakenly published prior to the version bumps of `zcash_address` and `zcash_encoding`.

Bump versions for f4jumble, zcash_address, zcash_encoding and zcash_history crates

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/address.rs
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/error.rs
zcash_client_backend/src/data_api/wallet.rs
zcash_client_sqlite/src/error.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/prepared.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/init/migrations/add_utxo_account.rs
zcash_primitives/CHANGELOG.md
zcash_primitives/src/zip32.rs

The legacy transparent address is never added to the `addresses` table, but we still need to be able to receive UTXOs sent to that address. So, we add a special case for when a UTXO matches that legacy address, and set the account ID to 0 manually.

Allow insertion of UTXOs associated with the legacy taddr.

---

zcash_client_sqlite/src/wallet.rs

Error message:
"Error while fetching transparent balances for AccountId(0): no such column: u.received_by_accountt"
Closes #686

get_transparent_balances fails with `no such column`

---

.gitattributes
.github/workflows/ci.yml
zcash_client_backend/.gitignore
zcash_client_backend/CHANGELOG.md
zcash_client_backend/Cargo.toml
zcash_client_backend/build.rs
zcash_client_backend/src/data_api/error.rs
zcash_client_backend/src/proto.rs
zcash_client_backend/src/proto/compact_formats.rs
zcash_client_backend/src/welding_rig.rs
zcash_client_sqlite/Cargo.toml
zcash_client_sqlite/src/chain.rs
zcash_client_sqlite/src/lib.rs

The latter is maintained by the Tokio developers, and has easy integration with the `tonic` gRPC library which is actively maintained.

zcash_client_backend: Switch from `protobuf 2` to `prost 0.11`

---

.gitattributes
zcash_client_backend/CHANGELOG.md
zcash_client_backend/Cargo.toml
zcash_client_backend/build.rs
zcash_client_backend/proto/service.proto
zcash_client_backend/src/proto.rs
zcash_client_backend/src/proto/service.rs

The lightwalletd service file is sourced from zcash/lightwalletd@ad5ecda5fbb5e12799f926b8cd785d54fdd250c8
Closes zcash/librustzcash#585.

zcash_client_backend: Add gRPC bindings behind feature flag

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api/error.rs
zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/fees.rs
zcash_client_backend/src/lib.rs
zcash_extensions/src/transparent/demo.rs
zcash_primitives/CHANGELOG.md
zcash_primitives/src/transaction/builder.rs
zcash_primitives/src/transaction/components/sapling.rs
zcash_primitives/src/transaction/components/sapling/builder.rs
zcash_primitives/src/transaction/components/sapling/fees.rs
zcash_primitives/src/transaction/components/transparent.rs
zcash_primitives/src/transaction/components/transparent/builder.rs
zcash_primitives/src/transaction/components/transparent/fees.rs
zcash_primitives/src/transaction/components/tze.rs
zcash_primitives/src/transaction/components/tze/builder.rs
zcash_primitives/src/transaction/components/tze/fees.rs
zcash_primitives/src/transaction/fees.rs
zcash_primitives/src/transaction/mod.rs

This introduces a FeeStrategy abstraction (and `FutureFeeStrategy` for `zfuture`) that can be used to compute fees and required change during the process of transaction build. This also modifies `TransactionBuilder` to require the caller to construct a change output directly, instead of doing so implicitly.

Update the transaction builder to make change outputs explicit

---

zcash_client_sqlite/src/wallet/init/migrations.rs
zcash_client_sqlite/src/wallet/init/migrations/add_transaction_views.rs

Un-mined transactions cannot currently be migrated to retroactively store fee information, because the encoding used to persist them is unknown.

Fix a bug in migrations when transaction block height is unknown.

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/address.rs
zcash_client_backend/src/data_api/error.rs
zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/encoding.rs
zcash_client_backend/src/keys.rs
zcash_client_backend/src/welding_rig.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/transact.rs
zcash_extensions/src/transparent/demo.rs
zcash_primitives/CHANGELOG.md
zcash_primitives/src/merkle_tree.rs
zcash_primitives/src/sapling.rs
zcash_primitives/src/transaction/builder.rs
zcash_primitives/src/transaction/components/sapling/builder.rs
zcash_primitives/src/zip32/sapling.rs

Correctly construct outputs when spending internal notes.

---

zcash_client_backend/src/proto.rs

Clippy currently fails on all PRs based on `main` due to linter errors in the generated protobuf code.

Fix clippy complaints about generated protobuf code.

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/Cargo.toml
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/Cargo.toml
zcash_extensions/Cargo.toml
zcash_primitives/CHANGELOG.md
zcash_primitives/Cargo.toml
zcash_proofs/CHANGELOG.md
zcash_proofs/Cargo.toml

Closes #487.
Closes #488.
Closes #497.

Release `zcash_client_sqlite 0.4.0` and dependencies

---

zcash_client_backend/src/proto/compact_formats.rs
zcash_client_backend/src/proto/service.rs

`prost 0.11.2` added code formatting support, so the generated files now better match what rustfmt produces.

Update generated protobufs

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api/wallet.rs
zcash_client_sqlite/src/wallet/transact.rs
zcash_primitives/src/transaction/components/transparent/builder.rs

Previously, the shielding threshold was fixed to 100000 zatoshis.
Fixes #726

Add `shielding_threshold` argument to `shield_transparent_funds`.

---

zcash_client_sqlite/src/lib.rs

Closes #742
This is mainly for FFI Display

Implement fmt::Display descriptions for FsBlockDbError

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api/chain.rs
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/src/chain.rs
zcash_client_sqlite/src/lib.rs

Closes zcash/librustzcash#705
This change adds a `limit` parameter to `validate_chain()` function and also makes the `validate_from` parameters non-optional to avoid falling back to `sapling_activation_height` which is an implicit default parameter that is visible to the caller and I consider it hurts the "locality" of the function itself. 
I have empirical reasons to suspect that these assumptions on DB state don’t hold up and it can trigger a DB rewind on clients using validate_chain without specifying a concrete `validate_from` value and that might make the clients delete the whole database.
If you pass None to the validate_from  parameter to a BlockSourceT that has blocks on it and does not start in sapling_activation  this will fail with a weird state that would signal a gap of …

Adds `limit` parameter to `validate_chain()`

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/data_api/wallet/input_selection.rs
zcash_client_sqlite/src/wallet/transact.rs

This change makes it possible for wallets using the `zcash_client_backend::data_api::wallet` module to perform transaction preparation, including input selection and fee calculation, as an independent step prior to creating proofs and signatures. This can be used to improve user experience by making it possible to report the proposed effects of the transaction to the wallet user (including privacy implications) prior to authorizing the transaction.

Factor out a transaction proposal API from `spend`.

---

.github/workflows/book.yml
.github/workflows/ci.yml
rust-toolchain.toml

The `actions-rs/*` actions are unmaintained. See actions-rs/toolchain#216 for more information.
- `actions-rs/toolchain` is replaced by `rust-toolchain.toml`.
- `actions-rs/cargo` is replaced by direct cargo usage.
- `actions-rs/tarpaulin` is replaced by the `cargo-tarpaulin` container.
We currently retain a few usages due to a current lack of alternatives:
- `actions-rs/toolchain` to enable beta (for Clippy warnings) and nightly (for building the book).
- `actions-rs/clippy-check` so Clippy results are published as annotations on PRs.
We also now require via `rust-toolchain.toml` that people building from the repo have the `clippy` and `rustfmt` components installed. This is fine because they will need to ensure these pass when making PRs.

CI: Replace most unmaintained `actions-rs/*` actions

---

.github/workflows/book.yml
.github/workflows/ci.yml

Now that dtolnay/rust-toolchain#53 has been closed, we can migrate away from the unmaintained actions-rs/toolchain.

CI: Replace `actions-rs/toolchain` with `dtolnay/rust-toolchain`

---

zcash_primitives/CHANGELOG.md
zcash_primitives/Cargo.toml
zcash_primitives/src/transaction/components/sapling.rs

Until zcash/zcash#6397 is closed, this ability is needed by `zcashd` for crossing the FFI.

Temporarily re-expose ability to construct invalid Sapling bundles

---

Cargo.toml
components/zcash_note_encryption/CHANGELOG.md
components/zcash_note_encryption/Cargo.toml
components/zcash_note_encryption/src/lib.rs
zcash_client_backend/Cargo.toml
zcash_client_sqlite/Cargo.toml
zcash_primitives/Cargo.toml

This then updates the `zcash_note_encryption` crate for a version 0.3.0 release.

zcash_note_encryption: remove `recipient` parameter from `Domain::note_plaintext_bytes`

---

zcash_proofs/CHANGELOG.md
zcash_proofs/Cargo.toml

This removes our reliance on the following out-of-date transitive dependencies that are duplicative of more recent versions of crates we depend on:
- bls12_381 v0.7
- ff v0.12
- group v0.12
- jubjub v0.9
- pasta_curves v0.4
- reddsa v0.3

Upgrade to redjubjub 0.7.0

---

zcash_primitives/CHANGELOG.md
zcash_primitives/Cargo.toml

`bip0039 0.11` switched from language function arguments to a generic parameter. We aren't ready to migrate to this yet.

zcash_primitives: Downgrade to `bip0039 0.10`

---

zcash_history/Cargo.toml
zcash_history/src/node_data.rs
zcash_history/src/tree.rs

Part of #757; resolves duplicate `rand-core` dependencies.
Best viewed ignoring whitespace changes.

Use proptest instead of quickcheck for zcash_history tests.

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/Cargo.toml
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/Cargo.toml
zcash_extensions/Cargo.toml
zcash_primitives/CHANGELOG.md
zcash_primitives/Cargo.toml
zcash_proofs/CHANGELOG.md
zcash_proofs/Cargo.toml

`zcash_primitives 0.11.0`, `zcash_proofs 0.11.0`, `zcash_client_backend 0.8.0`, `zcash_client_sqlite 0.6.0`

---

components/zcash_address/CHANGELOG.md
components/zcash_address/Cargo.toml

This is just so we don't have two `bech32` versions in `zcashd`.

`zcash_address 0.2.1`

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/chain.rs
zcash_client_backend/src/decrypt.rs
zcash_client_backend/src/wallet.rs
zcash_client_backend/src/welding_rig.rs
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/src/chain.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/prepared.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/transact.rs

This helps to clarify the Sapling-specific nature of a number of operations in wallet code.

Remove deprecated APIs & rename Sapling-specific data structures to include "Sapling".

---

zcash_history/CHANGELOG.md
zcash_history/Cargo.toml

We also disable the default `std` feature, to remove transitive dependencies we don't use.

zcash_history: Migrate to `primitive-types 0.12`

---

zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/fees/fixed.rs
zcash_client_sqlite/src/wallet/transact.rs
zcash_extensions/src/transparent/demo.rs
zcash_primitives/CHANGELOG.md
zcash_primitives/src/transaction/builder.rs
zcash_primitives/src/transaction/components/amount.rs
zcash_primitives/src/transaction/fees/fixed.rs
zcash_primitives/src/transaction/fees/zip317.rs

#830 updated `zcash_primitives::components::amount::DEFAULT_FEE` to be 10000 zatoshis. This is not consistent with the value of `LEGACY_DEFAULT_FEE` in zcashd, and might have unintended side effects in code that uses it. Also, the effect on the behaviour of `zcash_primitives::transaction::fees::fixed::FeeRule::standard()` was not documented in the release notes.
This PR reverts #830 (as the first commit) and instead updates `zcash_primitives::transaction::fees::fixed::FeeRule::standard()` to use a new constant, `zcash_primitives::transaction::fees::zip317::MINIMUM_FEE`. It also deprecates `zcash_primitives::components::amount::DEFAULT_FEE` and `zcash_primitives::transaction::fees::fixed::FeeRule::standard()`. (You can still use `fixed::FeeRule` via its `non_standard` constructor, which is …

Revert #830 and instead modify `zcash_primitives::transaction::fees::fixed::FeeRule::standard()`

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet.rs

Memos may be absent for both sent and received notes in cases where only compact block information has been used to populate the wallet database. This fixes a potential crash in the case that we attempt to decode a SQLite `NULL` as a byte array. It does, however, introduce a slight semantic confusion that will need to be considered in the case of future updates where a note may not have an associated memo; at present, the only reason we might not have the memo is that we might not have retrieved the full transaction information from the chain, but in the future there might be other possible reasons for this absence.
Fixes #384

Update memo retrieval API to reflect that memos may not be present.

---

zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/Cargo.toml
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet.rs

Memos may be absent for both sent and received notes in cases where only compact block information has been used to populate the wallet database. This fixes a potential crash in the case that we attempt to decode a SQLite `NULL` as a byte array.
Fixes #384
(cherry picked from commit d99b4d4d6ec1126447159ffe649a3edac2f322d5)

Return the empty memo when memo is not present.

---

components/zcash_note_encryption/src/lib.rs
zcash_primitives/src/sapling/address.rs
zcash_primitives/src/sapling/note_encryption.rs

Avoid redundant checks during note decryption

---

Cargo.toml
components/zcash_note_encryption/CHANGELOG.md
components/zcash_note_encryption/src/lib.rs
zcash_primitives/src/sapling/note_encryption.rs

Requires https://github.com/zcash/orchard/pull/396
Fixes #850

Remove esk and ephemeral_key arguments from `parse_note_plaintext_ovk`

---

Cargo.toml
components/zcash_address/CHANGELOG.md
components/zcash_address/Cargo.toml
components/zcash_note_encryption/CHANGELOG.md
components/zcash_note_encryption/Cargo.toml
zcash_client_backend/CHANGELOG.md
zcash_client_backend/Cargo.toml
zcash_client_backend/src/welding_rig.rs
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/Cargo.toml
zcash_extensions/Cargo.toml
zcash_primitives/CHANGELOG.md
zcash_primitives/Cargo.toml
zcash_proofs/CHANGELOG.md
zcash_proofs/Cargo.toml

Upgrades to:
- `bs58 0.5`
- `incrementalmerkletree 0.4`
- `orchard 0.5`
Fixes #785

Release zcash_address 0.3.0, zcash_primitives 0.12.0 and zcash_proofs 0.12.0

---

zcash_client_backend/Cargo.toml
zcash_client_sqlite/Cargo.toml

This resolves [RUSTSEC-2022-0090](https://rustsec.org/advisories/RUSTSEC-2022-0090), and with both this patch and after I remembered to also run `cargo update`, there are now no `cargo audit` reports.
Note that this updates dependencies that are re-exported in the public interface, so I'm not super clear on if that's invasive for dependent crates or not. If it were invasive, it may imply something about our release versioning and semver, which I haven't thought about too carefully.

[Impacts API versioning] Update dependencies to resolve RUSTSEC-2022-0090

---

zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/fees/fixed.rs
zcash_client_backend/src/fees/zip317.rs
zcash_client_backend/src/keys.rs
zcash_extensions/src/transparent/demo.rs
zcash_primitives/CHANGELOG.md
zcash_primitives/src/consensus.rs
zcash_primitives/src/transaction/builder.rs
zcash_primitives/src/transaction/components/orchard.rs
zcash_primitives/src/transaction/fees.rs
zcash_primitives/src/transaction/fees/fixed.rs
zcash_primitives/src/transaction/fees/zip317.rs
zcash_primitives/src/transaction/mod.rs

Add Orchard to transaction builder

---

zcash_proofs/CHANGELOG.md
zcash_proofs/Cargo.toml
zcash_proofs/src/lib.rs

`directories 5.0.1` added a dependency on `option-ext`, which is licensed as MPL (a copyleft license), and which upstream intends to keep (dirs-dev/dirs-sys-rs#21). The replacement dependencies are all licensed as `MIT OR Apache-2.0`.

Replace `directories` dependency with `home, known-folders, xdg`

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/chain.rs
zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/scanning.rs
zcash_client_sqlite/src/chain.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/init/migrations/ufvk_support.rs
zcash_client_sqlite/src/wallet/init/migrations/v_transactions_net.rs
zcash_client_sqlite/src/wallet/sapling.rs

zcash_client_backend: Make scan range bounds required in `data_api::chain::scan_cached_blocks`

---

zcash_client_backend/src/data_api.rs
zcash_client_backend/src/scanning.rs
zcash_client_sqlite/src/chain.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/init/migrations.rs
zcash_client_sqlite/src/wallet/init/migrations/nullifier_map.rs
zcash_client_sqlite/src/wallet/sapling.rs

Also fixes the `WalletDb::block_fully_scanned` implementation, which this PR depends on.

zcash_client_sqlite: Maintain a nullifier map from out-of-order scanning

---

zcash_client_sqlite/src/wallet/init/migrations/shardtree_support.rs

We only need to load frontiers into the ShardTree that are close enough to the wallet's known chain tip to fill `PRUNING_DEPTH` checkpoints, so that ShardTree's witness generation will be able to correctly handle anchor depths. Loading frontiers further back than this doesn't add any useful nodes to the ShardTree (as we don't support rollbacks beyond `PRUNING_DEPTH`, and we won't be finding notes in earlier blocks), and hurts performance (as frontier importing has a significant Merkle tree hashing cost).
Closes zcash/librustzcash#877.

zcash_client_sqlite: Only import recent frontiers into `ShardTree`

---

Cargo.toml
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/Cargo.toml
zcash_client_sqlite/src/lib.rs

The new `multicore` feature flag can be used to disable this behaviour.
Depends on https://github.com/zcash/incrementalmerkletree/pull/88.

zcash_client_sqlite: Build subtrees from new commitments in a threadpool

---

zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/Cargo.toml
zcash_client_sqlite/src/error.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/commitment_tree.rs
zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/init/migrations/shardtree_support.rs

The `add_checkpoint` method is intended to be idempotent. In the case that we add a checkpoint at an already-checkpointed block height, we should only raise an error in the case that the note commitment tree position or the set of notes spent in the checkpointed block has changed.

zcash_client_sqlite: Ensure that re-adding the same checkpoint information does not cause a database conflict.

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/wallet.rs
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/init/migrations/sapling_memo_consistency.rs
zcash_client_sqlite/src/wallet/sapling.rs

Restrict use of backend-specific note identifiers.

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/wallet.rs
zcash_client_sqlite/src/chain.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/sapling.rs
zcash_client_sqlite/src/wallet/scanning.rs

Prior to the scan-before-sync changes, the wallet was able to assume that the maximum scanned block height at the time of the spend was within a few blocks of the chain tip. However, under linear scanning after the spend-before-sync changes this invariant no longer holds, resulting in a situation where in linear sync conditions the wallet could attempt to create transactions with already-past expiry heights.
This change separates the notion of "chain tip" from "max scanned height", relying upon the `scan_queue` table to maintain the wallet's view of the consensus chain height and using information from the `blocks` table only in situations where the latest and/or earliest scanned height is required.
As part of this change, the `WalletRead` interface is also modified to disambiguate these …

zcash_client_sqlite: Ensure that target and anchor heights are relative to the chain tip.

---

zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/init/migrations.rs
zcash_client_sqlite/src/wallet/init/migrations/v_sapling_shard_unscanned_ranges.rs
zcash_client_sqlite/src/wallet/sapling.rs

This change modifies the implementation of `get_spendable_sapling_notes` and `select_spendable_sapling_notes` to only return notes at positions where the associated note commitment tree shard has been fully scanned. This is slightly more conservative than it needs to be, because there could be cases where witnesses imported into the tree in the `shardtree_support` migration cover the complete range of a subtree (and hence that subtree doesn't need to be re-scanned). However, we can't detect or depend upon that condition in general without attempting to create a witness for each note retrieved.
A possible alternative to this approach would be to not bound our query results on the requested total, and instead attempt to construct a witness for each note we retrieve, skipping the note if we …

zcash_client_sqlite: Only select notes for which witnesses can be constructed.

---

zcash_client_backend/src/data_api/scanning.rs
zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/init/migrations.rs
zcash_client_sqlite/src/wallet/init/migrations/shardtree_support.rs
zcash_client_sqlite/src/wallet/init/migrations/v_sapling_shard_unscanned_ranges.rs
zcash_client_sqlite/src/wallet/scanning.rs

This is a partial solution to #902 and #898. The complete fix, which avoids the need to fully scan the subtree containing the wallet's birthday height, will be achievable once #901 is complete. 
Fixes #902
Fixes #898

zcash_client_sqlite: Initialize the scan queue as part of `init_blocks_table`

---

zcash_client_backend/src/keys.rs

This fixes a simple copy/paste error of the docs from the unified viewing key.

Fix API doc comment on UnifiedSpendingKey

---

zcash_client_sqlite/src/chain.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/testing.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/commitment_tree.rs
zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/init/migrations/add_transaction_views.rs
zcash_client_sqlite/src/wallet/init/migrations/received_notes_nullable_nf.rs
zcash_client_sqlite/src/wallet/init/migrations/v_transactions_net.rs
zcash_client_sqlite/src/wallet/sapling.rs
zcash_client_sqlite/src/wallet/scanning.rs

These provide a standard way to set up tests, and helper methods for performing common test actions.
Closes #917.

`zcash_client_sqlite`: Introduce `TestBuilder` and `TestRunner`

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/build.rs
zcash_client_backend/src/proto.rs
zcash_client_backend/src/proto/service.rs

The `zcash_client_backend::proto::service::compact_tx_streamer_client` is now the only module controlled by that feature flag, exposing the service types for use by parsers.

zcash_client_backend: Reduce scope of `lightwalletd-tonic` feature flag

---

zcash_client_sqlite/src/testing.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/scanning.rs

zcash_client_sqlite: Prevent scan range fragmentation.

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/Cargo.toml
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/proto.rs
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/src/chain.rs
zcash_client_sqlite/src/error.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/testing.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/init/migrations.rs
zcash_client_sqlite/src/wallet/init/migrations/add_account_birthdays.rs
zcash_client_sqlite/src/wallet/init/migrations/addresses_table.rs
zcash_client_sqlite/src/wallet/init/migrations/v_sapling_shard_unscanned_ranges.rs
zcash_client_sqlite/src/wallet/sapling.rs
zcash_client_sqlite/src/wallet/scanning.rs

zcash_client_backend: Add account birthday management to the Data Access API

---

zcash_client_sqlite/src/wallet/sapling.rs
zcash_client_sqlite/src/wallet/scanning.rs

This also factors out and cleans up repeated code that checks for anchor shard completeness.

zcash_client_sqlite: Add a test demonstrating chain tip fund unavailability

---

.github/workflows/ci.yml

This ensures that we catch non-MSRV compilation breakages caused by SemVer updates.

CI: Add job to build with latest Rust and dependencies

---

zcash_client_sqlite/src/testing.rs
zcash_client_sqlite/src/wallet/sapling.rs
zcash_primitives/CHANGELOG.md
zcash_primitives/src/transaction/components/amount.rs

This was originally going to test #899, and then it was going to test and fix #936. These tasks ended up being more complicated than we thought given the inconsistent use of the `sent_notes` table, and the introduction of out-of-order scanning (which can cause us not to know which spent notes are ours during the process of trying to categorize outputs). Now the PR just improves the existing wallet tests, provides support for resetting a wallet in the test framework, and checks that resetting a wallet works at all.

Improve wallet tests

---

Cargo.lock
zcash_client_backend/Cargo.toml
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/Cargo.toml

This is the release stabilization branch for:
* `zcash_primitives 0.13.0`
* `zcash_proofs 0.13.0`
* `zcash_client_backend 0.10.0`
* `zcash_client_sqlite 0.8.0`

Release stabilization branch for updates related to the 2.0.0 release of the light wallet SDKs

---

zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/init/migrations.rs
zcash_client_sqlite/src/wallet/init/migrations/v_tx_outputs_use_legacy_false.rs

At present, [zcash/zcash-android-wallet-sdk] supports Android API 27, which bundles SQLite 3.19. SQLite support for the `TRUE` and `FALSE` constants were introduced in SQLite 3.23, so we cannot currently use these constants and retain support for Android API 27.
This version support limitation applies only to the `v_transactions` and `v_tx_outputs` views, which are considered part of the public API of this crate; other use of more recent SQLite features is fine because they rely upon the SQLite bundled via our use of the `rusqlite` crate and feature compatibility is verified via the unit tests of this crate.

zcash_client_sqlite: Remove use of boolean constants from `v_tx_outputs`

---

zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/commitment_tree.rs
zcash_client_sqlite/src/wallet/init/migrations/shardtree_support.rs
zcash_client_sqlite/src/wallet/scanning.rs

We don't need to iterate over them, but the `*_extrema` internal methods are semantically returning inclusive ranges, and using `RangeInclusive` avoids bugs where the wrong half of the tuple is used (instead moving the location of the tuple handling inside the `*_extrema` methods, which cuts the number of occurrences from linear in the number of function calls to constant).

zcash_client_sqlite: Replace internal height tuples with `RangeInclusive`

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api/chain.rs
zcash_client_sqlite/Cargo.toml
zcash_client_sqlite/src/chain.rs
zcash_client_sqlite/src/testing.rs

When scanning, a wallet only needs to update balance and transaction information shown to users when the scan has resulted in a change to wallet state. This modifies `scan_cached_blocks` to return the range of block heights actually scanned, along with the counts of notes spent and received by the wallet in that range.
Fixes #918

zcash_client_backend: Return summary information from `scan_cached_blocks`

---

.github/workflows/ci.yml

`cargo tarpaulin` has changed the case of one of its config options.

CI: Fix Codecov check

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/data_api/wallet/input_selection.rs
zcash_client_backend/src/fees.rs
zcash_client_backend/src/fees/fixed.rs
zcash_client_backend/src/fees/zip317.rs
zcash_client_backend/src/scanning.rs
zcash_client_sqlite/src/chain.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/testing.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/sapling.rs
zcash_client_sqlite/src/wallet/scanning.rs
zcash_extensions/src/transparent/demo.rs
zcash_primitives/CHANGELOG.md
zcash_primitives/src/sapling/note_encryption.rs
zcash_primitives/src/transaction/builder.rs
zcash_primitives/src/transaction/components/amount.rs
zcash_primitives/src/transaction/fees.rs
zcash_primitives/src/transaction/fees/fixed.rs
zcash_primitives/src/transaction/fees/zip317.rs

It's incorrect to use the possibly-negative `Amount` type in places where values must be nonnegative.
This updates fee and change data structures to use `NonNegativeAmount` where possible.

zcash_client_backend: Use `NonNegativeAmount` for fee and change amounts.

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/fees.rs
zcash_client_backend/src/fees/fixed.rs
zcash_client_backend/src/fees/zip317.rs
zcash_client_sqlite/src/chain.rs
zcash_client_sqlite/src/testing.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/sapling.rs

The existing API limited change outputs to having only a single memo repeated across each change output. This change makes it so that each proposed change output can have its own associated memo, and leaves it up to the input selector to determine how requested change memos are associated with change outputs.

zcash_client_backend: Move change memos into the `ChangeValue` components of `Proposal`s

---

zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/init/migrations.rs
zcash_client_sqlite/src/wallet/init/migrations/v_transactions_note_uniqueness.rs

The `v_transactions` view is built upon the set of received notes, received note values being added to the balance for the transaction and spent notes being deducted from this balance. This fixes an error wherein if multiple identically-valued notes were spent in a transaction, only one of those notes' values was being counted as having been spent.

zcash_client_sqlite: Fix incorrect note deduplication in `v_transactions`

---

Cargo.lock
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/Cargo.toml

This is a special hotfix release to fix a high impact bug fixed by #1020. This branch is based off of the `zcash_client_sqlite-0.8.0` tag. We'll tag this after review and merge. (We'll have to manually merge though because of changelog conflicts...)
The alternative would be to release what's on `main` now, which also contains the bugfix, but that will be very intense process as `main` is not currently in a releasable state.

Release zcash_client_sqlite 0.8.1

---

zcash_extensions/src/transparent/demo.rs
zcash_primitives/CHANGELOG.md
zcash_primitives/src/sapling/address.rs
zcash_primitives/src/sapling/circuit.rs
zcash_primitives/src/sapling/note_encryption.rs
zcash_primitives/src/sapling/prover.rs
zcash_primitives/src/transaction/builder.rs
zcash_primitives/src/transaction/components/amount.rs
zcash_proofs/src/sapling/prover.rs

zcash_primitives: Use sapling::NoteValue instead of bare u64

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/fees.rs
zcash_client_backend/src/fees/standard.rs
zcash_client_sqlite/src/testing.rs
zcash_client_sqlite/src/wallet/sapling.rs
zcash_primitives/CHANGELOG.md
zcash_primitives/src/transaction/fees.rs

In order to pass a `FeeRule` across a serialization boundary, it is necessary for the type of the fee rule to be known. The simplest approach to this is to add serialization for a fixed set of types. `StandardFeeRule` provides such a set of known fee rules, so that we can serialize and deserialize them.
Extracted from #891

Add an enumeration of standard fee rules.

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/data_api/wallet/input_selection.rs
zcash_client_sqlite/src/testing.rs
zcash_client_sqlite/src/wallet/sapling.rs

Builds upon #1018 
This fixes an API issue whereby it was possible to execute a `Proposal`
with a different value of `min_confirmations` than that with which the
`Proposal` was constructed.

zcash_client_backend: Move `min_confirmations` into `Proposal`

---

zcash_client_backend/src/data_api/wallet.rs
zcash_client_sqlite/src/testing.rs
zcash_client_sqlite/src/wallet/sapling.rs
zcash_extensions/src/transparent/demo.rs
zcash_primitives/benches/note_decryption.rs
zcash_primitives/src/sapling.rs
zcash_primitives/src/sapling/value.rs
zcash_primitives/src/sapling/value/sums.rs
zcash_primitives/src/transaction/builder.rs
zcash_primitives/src/transaction/components/sapling.rs
zcash_primitives/src/transaction/components/sapling/builder.rs
zcash_primitives/src/transaction/mod.rs

Closes zcash/librustzcash#741.

Refactor Sapling builder to separate out proof generation

---

.github/workflows/ci.yml

This target is incompatible with various crates that we use for testing. However, when those crates are enabled via dev-dependencies, they become part of the build graph and prevent us from building the regular code.
Downstream crates don't inherit dev-dependencies, so we simulate this directly in CI.

CI: Build `wasm32-wasi` in a synthetic crate

---

zcash_primitives/src/transaction/components/sapling/builder.rs

This enables unauthorized Sapling bundles to be cloned, for example when loading them into a `TransactionData` for signature hashing.

zcash_primitives: Implement `Clone` on bundle marker types

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
zcash_client_backend/CHANGELOG.md
zcash_client_backend/Cargo.toml
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/data_api/wallet/input_selection.rs
zcash_client_backend/src/fees.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/testing.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/commitment_tree.rs
zcash_client_sqlite/src/wallet/sapling.rs
zcash_primitives/src/transaction/sighash.rs

Prior to this change, it's necessary to implement the entirety of the `WalletRead` trait in order to be able to use the input selection functionality provided by `zcash_client_backend::data_api::input_selection`. This change factors out the minimal operations required for transaction proposal construction to better reflect the principle of least authority and make the input selection code reusable in more contexts.

zcash_client_backend: Factor out `InputSource` from `WalletRead`

---

.gitattributes
zcash_client_backend/CHANGELOG.md
zcash_client_backend/build.rs
zcash_client_backend/proto/proposal.proto
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/error.rs
zcash_client_backend/src/data_api/wallet/input_selection.rs
zcash_client_backend/src/fees.rs
zcash_client_backend/src/proto.rs
zcash_client_backend/src/proto/proposal.rs
zcash_client_backend/src/wallet.rs
zcash_client_backend/src/zip321.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/testing.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/sapling.rs
zcash_primitives/CHANGELOG.md
zcash_primitives/src/memo.rs
zcash_primitives/src/sapling/note.rs

In order to make complete information about proposed transactions readily available to wallets, it's necessary to provide a mechanism to pass a `TransactionProposal` across the FFI. This PR adds a Protobuf representation for proposed transactions and implements conversions back and forth between the protobuf representation and the native type.

Add protobuf representation for transaction proposals

---

zcash_client_backend/src/proto/proposal.rs

A comment change to the source file was made in zcash/librustzcash#891 before merging, but the generated file was not updated to match.

Fix generated protobuf file to match source

---

zcash_primitives/CHANGELOG.md
zcash_primitives/benches/note_decryption.rs
zcash_primitives/src/sapling/builder.rs
zcash_primitives/src/sapling/bundle.rs
zcash_primitives/src/sapling/note_encryption.rs
zcash_primitives/src/sapling/value.rs
zcash_primitives/src/sapling/verifier.rs
zcash_primitives/src/sapling/verifier/batch.rs
zcash_primitives/src/sapling/verifier/single.rs
zcash_primitives/src/transaction/builder.rs
zcash_primitives/src/transaction/components/sapling.rs
zcash_primitives/src/transaction/mod.rs
zcash_primitives/src/transaction/txid.rs

This removes the dependency on `Amount`, and matches how we handle this in the `orchard` crate.
Part of zcash/librustzcash#1044.

zcash_primitives: Make `value_balance` generic in `sapling::Bundle`

---

zcash_client_backend/src/data_api/wallet.rs
zcash_extensions/src/transparent/demo.rs
zcash_primitives/CHANGELOG.md
zcash_primitives/src/sapling/builder.rs
zcash_primitives/src/transaction/builder.rs

The note provided to `add_sapling_spend` contains the recipient address, and we can extract the diversifier from this address, so we should not pass it separately.

Avoid passing duplicate diversifier information to Sapling builder.

---

zcash_extensions/Cargo.toml
zcash_extensions/src/transparent/demo.rs
zcash_primitives/Cargo.toml
zcash_primitives/src/consensus.rs
zcash_primitives/src/transaction/mod.rs

I've started working on adding Network Upgrade 6 to Zebra. I need to add it to `zcash_primitives` as well as `zebra-chain` and `zebra-scan` both depend on it.
In this code NU6 references Tx V5. This will need to be updated to reference Tx V6 and ZIP-230 once Tx V6 is implemented.
Let me know if this is not the right way to proceed here.
cc @teor2345

Add Network Upgrade 6 to `consensus::NetworkUpgrade`

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/error.rs
zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/data_api/wallet/input_selection.rs
zcash_client_backend/src/lib.rs
zcash_client_backend/src/proto.rs
zcash_client_backend/src/scanning.rs
zcash_client_backend/src/wallet.rs
zcash_client_sqlite/src/error.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/init/migrations.rs
zcash_client_sqlite/src/wallet/init/migrations/receiving_key_scopes.rs
zcash_client_sqlite/src/wallet/init/migrations/ufvk_support.rs
zcash_client_sqlite/src/wallet/init/migrations/v_transactions_net.rs
zcash_client_sqlite/src/wallet/sapling.rs
zcash_primitives/CHANGELOG.md
zcash_primitives/src/transaction/components/amount.rs

This generalizes the data structure used to represent spendable notes to handle both Sapling and Orchard notes.

Replace `SaplingReceivedNote` with `ReceivedNote`

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/Cargo.toml
zcash_client_backend/src/address.rs
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/keys.rs
zcash_client_backend/src/lib.rs
zcash_client_backend/src/proto.rs
zcash_client_backend/src/scanning.rs
zcash_client_backend/src/wallet.rs
zcash_client_backend/src/zip321.rs
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/Cargo.toml
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/testing.rs
zcash_client_sqlite/src/wallet.rs
zcash_extensions/src/transparent/demo.rs
zcash_primitives/src/transaction/builder.rs

We plan to also introduce a similar flag to gate access to Sapling functionality. Since introduction of Orchard functionality is still nascent, it's the correct time to introduce this isolation, before there's more functionality that needs to be isolated in this fashion.

zcash_client_backend: Introduce an "orchard" feature flag.

---

.vscode/settings.json

This improves the editing experience by 'enabling' all the code that otherwise is turned off because of the `unstable` flag.

Enable unstable features when editing in VS Code

---

zcash_client_backend/Cargo.toml
zcash_client_backend/src/lib.rs
zcash_client_sqlite/Cargo.toml
zcash_client_sqlite/src/lib.rs
zcash_extensions/Cargo.toml
zcash_extensions/src/lib.rs
zcash_primitives/Cargo.toml
zcash_primitives/src/lib.rs
zcash_primitives/src/transaction/builder.rs
zcash_primitives/src/transaction/components/transparent/builder.rs
zcash_proofs/Cargo.toml
zcash_proofs/src/lib.rs
zcash_proofs/src/prover.rs

This can be rendered locally with:
```
RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --no-deps --workspace --all-features
```

Show feature flags in documentation

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/data_api/wallet/input_selection.rs
zcash_client_backend/src/proto.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/testing.rs
zcash_client_sqlite/src/wallet.rs

This unification allows us to better isolate transparent-input dependent functionality. Previously, `TransparentInputSource` could not be placed under a feature flag because the interface was needed for proposal deserialization; by instead making the transparent input source methods flag-dependent, we can correctly produce an error when proposal deserializaiton attempts to select transparent inputs and the feature flag is off.

Replace SaplingInputSource and TransparentInputSource with InputSource

---

zcash_client_sqlite/Cargo.toml

Nothing seems to have depended on it, and my testing suggests the same build of this crate can work on both networks.

Drop unused `mainnet` feature

---

Cargo.lock
zcash_client_backend/CHANGELOG.md
zcash_client_backend/README.md
zcash_client_backend/proto/proposal.proto
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/data_api/wallet/input_selection.rs
zcash_client_backend/src/fees.rs
zcash_client_backend/src/fees/common.rs
zcash_client_backend/src/fees/fixed.rs
zcash_client_backend/src/fees/orchard.rs
zcash_client_backend/src/fees/standard.rs
zcash_client_backend/src/fees/zip317.rs
zcash_client_backend/src/proto.rs
zcash_client_backend/src/proto/proposal.rs
zcash_client_backend/src/wallet.rs
zcash_client_sqlite/Cargo.toml
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet/sapling.rs
zcash_primitives/CHANGELOG.md
zcash_primitives/src/transaction/components/amount.rs

Now builds atop #1090
Part of #403.
Closes #1094.
Closes #1097.

Add Orchard support to fees & transaction proposals.

---

.editorconfig
zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet.rs

As per our [discord discussion](https://discord.com/channels/809218587167293450/972649509651906711/1193920166598287421), this needs to be exposed via the API since the sqlite 'public API' is said to not include most of the tables, including the accounts table.

Add `WalletRead::get_account_ids` function

---

Cargo.lock
Cargo.toml
zcash_client_backend/src/data_api/wallet.rs
zcash_extensions/src/transparent/demo.rs
zcash_primitives/CHANGELOG.md
zcash_primitives/src/transaction/builder.rs

This is best reviewed with whitespace changes hidden.

zcash_primitives: Add Orchard bundle metadata to transaction builder.

---

README.md
zcash_client_backend/README.md
zcash_client_sqlite/README.md
zcash_extensions/README.md
zcash_primitives/README.md
zcash_proofs/README.md

Remove notices about the BOSL license

---

zcash_client_backend/src/zip321.rs
zcash_keys/src/encoding.rs
zcash_primitives/CHANGELOG.md
zcash_primitives/Cargo.toml
zcash_primitives/src/consensus.rs
zcash_primitives/src/lib.rs
zcash_primitives/src/local_consensus.rs

Add regtest support to `Parameter` for Mobile SDKs

---

zcash_client_backend/Cargo.toml

Due to `zcash_keys` being in `zcash_client_backend`'s public API, their unstable APIs are a common API surface (as they were before `zcash_keys` was extracted).
This can be reverted once `zcash_keys` types with unstable APIs are not being re-exported from `zcash_client_backend`.

zcash_client_backend: Enable `zcash_keys/unstable` feature flag

---

.github/workflows/ci.yml
.gitignore
zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api/error.rs
zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/data_api/wallet/input_selection.rs
zcash_client_backend/src/lib.rs
zcash_client_backend/src/proto.rs
zcash_client_sqlite/src/wallet.rs
zcash_keys/CHANGELOG.md
zcash_keys/src/address.rs

Add `zcash_unstable` compiler flag to fully gate `orchard` functionality

---

.github/workflows/ci.yml

This is a little fragile as it requires we always add patch directives at the bottom of `Cargo.toml`, but that's indeed what we do.

CI: Copy patch directives into synthetic crate

---

.github/workflows/ci.yml

This reduces the number of macOS runner jobs in each PR from 10 to 6, or from 5 to 3 for external PRs. GitHub's macOS runners are noticeably slower than their other runners, and our available free runner slots are being quickly exhausted when we have multiple PRs open.

CI: Don't test `unstable-nu6` and `zfuture` feature flags on macOS

---

.vscode/settings.json

Necessary for the `--all-features` to work, allowing all code to be compiled by `rust-analyzer`.

Add `zcash_unstable` to `RUSTFLAGS` for VS Code

---

zcash_client_backend/src/zip321.rs
zcash_client_sqlite/Cargo.toml
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/init/migrations/add_transaction_views.rs
zcash_client_sqlite/src/wallet/init/migrations/addresses_table.rs
zcash_client_sqlite/src/wallet/init/migrations/ufvk_support.rs
zcash_keys/src/address.rs
zcash_keys/src/keys.rs

This default only made sense in the context of what was supported by `zcash_client_sqlite`, and not in any other context. Unified address requests no longer have their parts conditioned by what feature flags are available; instead, if a request is constructed for which the required key parts are not supported under a particular selection of feature flags, address generation will raise a runtime error.

zcash_keys: Remove `UnifiedAddressRequest::DEFAULT`

---

zcash_client_sqlite/src/wallet/sapling.rs
zcash_extensions/src/transparent/demo.rs
zcash_keys/src/address.rs
zcash_keys/src/encoding.rs
zcash_primitives/CHANGELOG.md
zcash_primitives/src/constants/mainnet.rs
zcash_primitives/src/constants/regtest.rs
zcash_primitives/src/constants/testnet.rs
zcash_primitives/src/legacy.rs
zcash_primitives/src/legacy/keys.rs
zcash_primitives/src/transaction/builder.rs
zcash_primitives/src/transaction/components/transparent/builder.rs
zcash_primitives/src/transaction/fees/zip317.rs

zcash_primitives: Rename `TransparentAddress` variants.

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/error.rs
zcash_client_backend/src/data_api/wallet.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/init/migrations/add_transaction_views.rs
zcash_client_sqlite/src/wallet/init/migrations/receiving_key_scopes.rs
zcash_keys/CHANGELOG.md
zcash_keys/src/address.rs
zcash_keys/src/keys.rs
zcash_primitives/CHANGELOG.md
zcash_primitives/src/legacy.rs
zcash_primitives/src/legacy/keys.rs
zcash_primitives/src/transaction/builder.rs

- Declare `NonHardenedChildIndex` struct
- Change `WalletRead::get_transparent_receivers` signature to use the new struct
It needn't return the account id that was given as an input, and it shouldn't return an 11-byte diversifier index when a 31-bit child index is more appropriate.

Declare and use NonHardenedChildIndex for transparent

---

Cargo.lock
Cargo.toml
zcash_client_backend/CHANGELOG.md
zcash_client_backend/proto/proposal.proto
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/error.rs
zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/data_api/wallet/input_selection.rs
zcash_client_backend/src/lib.rs
zcash_client_backend/src/proposal.rs
zcash_client_backend/src/proto.rs
zcash_client_backend/src/proto/proposal.rs
zcash_client_backend/src/wallet.rs
zcash_client_backend/src/zip321.rs
zcash_client_sqlite/Cargo.toml
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/testing.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/init/migrations/add_transaction_views.rs
zcash_client_sqlite/src/wallet/init/migrations/receiving_key_scopes.rs
zcash_client_sqlite/src/wallet/sapling.rs
zcash_keys/src/keys.rs
zcash_primitives/CHANGELOG.md
zcash_primitives/src/legacy.rs
zcash_primitives/src/legacy/keys.rs
zcash_primitives/src/transaction/builder.rs

Best reviewed commit-by-commit and with whitespace changes hidden.
* Add the chosen output pool for each payment to the proposal data.
* Move proposal-related types to their own module
* Make proposals able to represent multiple linked transactions, for ZIP 320

`zcash_client_backend`: Updates to the `Proposal` data structure

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/chain.rs
zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/data_api/wallet/input_selection.rs
zcash_client_backend/src/decrypt.rs
zcash_client_backend/src/scanning.rs
zcash_client_backend/src/wallet.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/testing.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/sapling.rs

This PR was extracted from #1175 in order to make the changes to `zcash_client_backend` usable without the additional generalizations to `zcash_client_sqlite` made by that PR.

zcash_client_backend: Make `AccountId` an associated type of `WalletRead`

---

Cargo.lock
zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_sqlite/Cargo.toml
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/testing.rs
zcash_keys/CHANGELOG.md
zcash_keys/src/keys.rs

This adds a mechanism that allows a caller to verify that a given seed generates the viewing key that is stored in the wallet for a specified account.
Fixes #1189

zcash_client_backend: Add `WalletRead::validate_seed`

---

Cargo.lock
Cargo.toml
components/zcash_address/CHANGELOG.md
components/zcash_address/Cargo.toml
components/zcash_address/src/convert.rs
components/zcash_address/src/encoding.rs
components/zcash_address/src/lib.rs
components/zcash_protocol/CHANGELOG.md
components/zcash_protocol/Cargo.toml
components/zcash_protocol/src/consensus.rs
components/zcash_protocol/src/constants/mainnet.rs
components/zcash_protocol/src/constants/regtest.rs
components/zcash_protocol/src/constants/testnet.rs

zcash_address 0.3.2: ZIP 320 TEX address support

---

zcash_client_backend/src/data_api/wallet.rs

This fixes cargo doc build when transparent-inputs feature is not specified

Fixed cargo doc build failure

---

zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/init/migrations/full_account_ids.rs
zcash_client_sqlite/src/wallet/sapling.rs

Closes #1203
This PR is best viewed with whitespace changes hidden.

zcash_client_sqlite: Only consider notes spendable when both seed fingerprint & key scope are available.

---

Cargo.lock
zcash_client_backend/CHANGELOG.md
zcash_client_backend/Cargo.toml
zcash_client_backend/src/data_api/wallet.rs
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/Cargo.toml

These releases should enable documentation to be built for the `zcash_client_backend 0.11` and `zcash_client_sqlite 0.9` versions, which had significant changes.
Backports #1228 onto `zcash_client_backend 0.11.0`.

`zcash_client_backend 0.11.1`, `zcash_client_sqlite 0.9.1` with doc fixes

---

zcash_client_sqlite/src/testing.rs
zcash_client_sqlite/src/testing/pool.rs
zcash_client_sqlite/src/wallet/commitment_tree.rs
zcash_client_sqlite/src/wallet/sapling.rs
zcash_client_sqlite/src/wallet/scanning.rs

These are all "single shielded pool" tests, and should pass for any shielded pool implemented in the wallet.
Best reviewed locally with:
```
git show HEAD --color-moved=zebra --color-moved-ws=allow-indentation-change
```

zcash_client_sqlite: Generalise Sapling tests

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
zcash_client_sqlite/Cargo.toml
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/testing.rs
zcash_client_sqlite/src/testing/pool.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/commitment_tree.rs
zcash_client_sqlite/src/wallet/orchard.rs
zcash_client_sqlite/src/wallet/scanning.rs

Almost all of these tests currently fail, as expected.
This PR also makes some fixes and improvements to the test harness, that arose from debugging the new Orchard code.

zcash_client_sqlite: Run single-shielded-pool tests on Orchard

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/testing.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/init/migrations.rs
zcash_client_sqlite/src/wallet/init/migrations/orchard_received_notes.rs
zcash_client_sqlite/src/wallet/init/migrations/orchard_shardtree.rs
zcash_client_sqlite/src/wallet/orchard.rs
zcash_client_sqlite/src/wallet/scanning.rs

zcash_client_sqlite: Add database tables for Orchard

---

zcash_client_backend/src/data_api.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/init/migrations/receiving_key_scopes.rs
zcash_client_sqlite/src/wallet/orchard.rs

zcash_client_sqlite: Implement Orchard scanning

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api/wallet/input_selection.rs
zcash_client_backend/src/fees.rs
zcash_client_backend/src/fees/common.rs
zcash_client_backend/src/fees/zip317.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/common.rs
zcash_client_sqlite/src/wallet/orchard.rs
zcash_client_sqlite/src/wallet/sapling.rs
zcash_client_sqlite/src/wallet/scanning.rs

`zcash_client_sqlite`: Add Orchard wallet support

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/wallet.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/init/migrations/full_account_ids.rs

Also, return the backend database's view of the matching UFVK.

Return partial matches when using `WalletRead::get_account_for_ufvk`.

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/init/migrations/full_account_ids.rs

Add `WalletRead::get_seed_account`

---

Cargo.lock
Cargo.toml
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/chain.rs
zcash_client_backend/src/data_api/wallet/input_selection.rs
zcash_client_backend/src/scanning.rs
zcash_client_sqlite/Cargo.toml
zcash_client_sqlite/src/chain.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/testing.rs
zcash_client_sqlite/src/testing/pool.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/init/migrations/receiving_key_scopes.rs
zcash_client_sqlite/src/wallet/sapling.rs
zcash_client_sqlite/src/wallet/scanning.rs

This fixes an error that was causing it to be impossible to make cross-pool transactions when an anchor was needed for each pool, but alternating blocks held only Sapling or only Orchard notes. Prior to this fix, checkpoints were only created in the note commitment tree for a block for whatever pool had activity within that block; for example, if a block contained Orchard actions but no Sapling inputs or outputs, only an Orchard checkpoint was being created.
The fix for this issue requires that the initial tree state for each pool be available for each range of scanned blocks, so that we can be sure that we know the correct note commitment tree to position to checkpoint in that pool for a block that contains no inputs or outputs for the pool. As an ancillary benefit, this then will make …

zcash_client_sqlite: Ensure that Orchard and Sapling checkpoints are always available for the same block heights.

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/proto.rs
zcash_client_sqlite/src/lib.rs

This PR only adds one of the needed APIs for the mobile SDKs; due to also refactoring the traits, I decided to split the other changes (which are themselves non-trivial) to a follow-on PR.

APIs for mobile SDKs

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/init/migrations/full_account_ids.rs

This exposes the kind of account (derived or imported, from which the ZIP 32 account index can be obtained), and enables the `WalletRead::Account` type to be looked up via `WalletRead::AccountId` instead of solely via the derivation parameters or UFVK.

Account APIs needed for the mobile SDKs

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/wallet/input_selection.rs
zcash_client_backend/src/wallet.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/testing/pool.rs
zcash_client_sqlite/src/wallet/common.rs
zcash_client_sqlite/src/wallet/orchard.rs
zcash_client_sqlite/src/wallet/sapling.rs

This is a pure refactoring that should result in no functional changes.

zcash_client_backend: Pure refactoring for note selection ergonomics.

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/testing.rs
zcash_client_sqlite/src/testing/pool.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/init/migrations/sapling_memo_consistency.rs
zcash_keys/src/keys.rs

This should never have had the behavior of returning an error on a missing txid in the first place; doing so conflates database corruption or connectivity errors with the ordinary case where data may not be available.
Best reviewed hiding whitespace changes.

zcash_client_backend: Make `WalletRead::get_transaction` return `Result<Option<Transaction>, _>`

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
zcash_client_backend/Cargo.toml
zcash_client_backend/src/proto.rs
zcash_client_backend/src/proto/service.rs

Closes #1269 
Note this regenerates the code-generated `proto/service.rs` file and the newer version is included in this PR. This is a minor change to the `zcash_client_backend` public API as these are exposed.

Disable the default features of the `tonic` and `tonic-build` crates to allow downstream consumers to build in Wasm

---

zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/init/migrations/full_account_ids.rs
zcash_keys/CHANGELOG.md
zcash_keys/src/address.rs
zcash_keys/src/keys.rs
zcash_keys/src/lib.rs

Add `UnifiedIncomingViewingKey` struct

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_sqlite/Cargo.toml
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet/init.rs

During wallet migration in particular, the absence of _any_ accounts is expected, and all seeds should be treated as relevant (because accounts cannot be added before a wallet is initialized).

Distinguish seed relevance when no derived accounts are present

---

zcash_client_backend/src/proto.rs

zcash_client_backend: Treat protobuf default as the empty `CommitmentTree`.

---

zcash_client_backend/src/data_api/mem_wallet.rs

Needed for building the branch locally.

Fix the memory wallet build by hiding orchard fields in `new()` behind a flag

---

zcash_client_sqlite/src/wallet/init.rs

These tests were broken by #1291

zcash_client_sqlite: Fix tests that broke with the addition of Orchard UA receivers.

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/zip321.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/testing.rs
zcash_client_sqlite/src/testing/pool.rs
zcash_client_sqlite/src/wallet/orchard.rs
zcash_client_sqlite/src/wallet/sapling.rs

This fixes, but does not yet reproduce the bug in #1302, which is likely the same as the bug in #1294.
The error occurs as a consequence of checkpoints that were added for "companion" heights in the other tree being pruned after the nodes that were associated with those checkpoints had been previously pruned. This could occur because updates to the note commitment trees were done in two stages:
* In the initial stage, the tree state is updated for a scanned range, which may trigger pruning of previous checkpoints.
* In the second stage, the "missed" companion checkpoints are re-added to the tree, even if the leaf positions that they were referring to had already been pruned.
* When _those_ checkpoints are later pruned, multiple checkpoints are associated with a single internal node in the …

zcash_client_sqlite: Fix a problem related to checkpoint pruning.

---

zcash_client_backend/src/data_api/chain.rs
zcash_client_backend/src/scanning.rs
zcash_client_sqlite/src/lib.rs

This fixes an error wherein a note commitment in the last note commitment position in a block was not being correctly marked as a checkpoint.
This would occur when a block contained both Sapling and Orchard note commitments, but the final transaction in the block contained only either Sapling or Orchard note commitments, but not both.
Fixes #1302

zcash_client_backend: Ensure checkpoint at the end of each block.

---

zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/testing.rs
zcash_client_sqlite/src/testing/pool.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/common.rs
zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/init/migrations.rs
zcash_client_sqlite/src/wallet/init/migrations/full_account_ids.rs
zcash_client_sqlite/src/wallet/init/migrations/orchard_received_notes.rs
zcash_client_sqlite/src/wallet/orchard.rs
zcash_client_sqlite/src/wallet/sapling.rs
zcash_client_sqlite/src/wallet/scanning.rs

This fixes the remainder of the tests that were broken by the Orchard migration.
Fixes #1265

zcash_client_sqlite: Use account birthday subtree sizes for progress

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/decrypt.rs
zcash_client_backend/src/wallet.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/testing/pool.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/orchard.rs
zcash_client_sqlite/src/wallet/sapling.rs
zcash_client_sqlite/src/wallet/transparent.rs

zcash_client_sqlite: Use consistent criteria for detecting what accounts fund a transaction.

---

.github/workflows/ci.yml
zcash_client_sqlite/Cargo.toml
zcash_client_sqlite/src/wallet/common.rs
zcash_client_sqlite/src/wallet/orchard.rs
zcash_client_sqlite/src/wallet/sapling.rs
zcash_primitives/Cargo.toml
zcash_primitives/src/transaction/tests.rs
zcash_proofs/Cargo.toml
zcash_proofs/src/circuit/sprout/mod.rs

At present, we don't take builder padding rules into account in the determination of whether or not we can include spends of dust notes in grace actions. It's too complex to attempt a complete fix for Zashi 1.0, but we can have a tolerable workaround for launch by just never selecting dust-valued notes.

zcash_client_sqlite: Disallow selection of dust notes.

---

Cargo.lock
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/Cargo.toml
zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/init/migrations/full_account_ids.rs

zcash_client_sqlite: Fix sent note recipient constraint

---

Cargo.lock
zcash_client_backend/CHANGELOG.md
zcash_client_backend/Cargo.toml
zcash_client_backend/src/data_api/wallet/input_selection.rs
zcash_client_sqlite/src/testing/pool.rs
zcash_client_sqlite/src/wallet/orchard.rs
zcash_client_sqlite/src/wallet/sapling.rs

The "avoid pool crossing" conditions in note selection were erroneously not taking into account the need to pay transparent outputs.

zcash_client_sqlite: Fix incorrect input selection filtering when sending to transparent.

---

.github/actions/prepare/action.yml
Cargo.lock
zcash_client_backend/CHANGELOG.md
zcash_client_backend/Cargo.toml
zcash_client_backend/src/data_api/chain.rs
zcash_client_backend/src/lib.rs
zcash_client_backend/src/sync.rs

This implements the necessary state machine for taking a wallet in some arbitrary synchronization status, and fully scanning (the remainder of) the chain.
Closes zcash/librustzcash#1169.

zcash_client_backend: Implement async wallet synchronization function

---

Cargo.lock
Cargo.toml
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/mem_wallet.rs
zcash_client_backend/src/wallet.rs

I want to create the most basic version of a `put_blocks` function for the memory wallet, one where we assume that the blocks will be in order. 
This PR is for @nuttycom to take a look, it has some comments and questions in the code and also review comments.

Basic `put_block` function for the memory wallet

---

components/equihash/src/lib.rs
components/equihash/src/minimal.rs
components/equihash/src/params.rs
components/equihash/src/test_vectors/invalid.rs
components/equihash/src/test_vectors/valid.rs
components/equihash/src/verify.rs

Move-only; my main motivation is moving the minimal-encoding functions into a separate submodule, so that the inverse functions introduced in #1083 can also be placed there (with round-trip tests and proptests).

Refactor `equihash` code

---

.github/workflows/audits.yml
Cargo.lock
deny.toml
supply-chain/audits.toml
supply-chain/config.toml
supply-chain/imports.lock

This starts the process of removing our dependency on `zcash/zcash` for our `cargo-vet` audits. We import audits from there and other upstreams to bootstrap audits here; once this PR merges, we'll include this repo into our aggregated audit set, and then we can use audits here (for the MSRV-compatible dependencies pinned in this repo's `Cargo.lock`) to augment the audits done in our end binary repos (`zcashd` and the mobile SDKs, which use as close to stable Rust as we can).

Set up Cargo audit infrastructure

---

Cargo.lock
zcash_primitives/CHANGELOG.md
zcash_primitives/Cargo.toml
zcash_primitives/src/lib.rs
zcash_primitives/src/zip339.rs

Supercedes #1377. This helps with Arti support in Zebra. See https://github.com/zcash/librustzcash/pull/1377#issuecomment-2098664351 for discussion.

Remove zcash_primitives::zip339 module

---

Cargo.lock
Cargo.toml
zcash_primitives/CHANGELOG.md
zcash_primitives/Cargo.toml

The only default-enabled feature flag in `sapling-crypto` is the `multicore` feature flag, which we re-export in each crate that includes proof creation. We need to disable it as a default feature of our dependency in order to enable it to be correctly disabled when a user of e.g. `zcash_primitives` disables its default features.

Disable `sapling-crypto` default features by default

---

Cargo.lock
Cargo.toml
supply-chain/audits.toml
supply-chain/config.toml
supply-chain/imports.lock
zcash_client_backend/Cargo.toml
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/Cargo.toml
zcash_client_sqlite/src/error.rs
zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/init/migrations/add_utxo_account.rs
zcash_keys/CHANGELOG.md
zcash_keys/Cargo.toml
zcash_keys/src/keys.rs
zcash_primitives/CHANGELOG.md
zcash_primitives/Cargo.toml
zcash_primitives/src/legacy/keys.rs

As part of this, we migrate to `secp256k1 0.27`. This version does not bump `secp256k1-sys`, so remains compatible with the `libsecp256k1` revision used in `zcashd`.
The `zcash_primitives::legacy::keys::AccountPrivKey` encoding also changes to preserve the transparent extended key metadata. Previously the type was documented as such, but only encoded the private key and chain code; the new encoding now matches the documentation. As a side effect, the unstable encoding of `zcash_keys::keys::UnifiedSpendingKey` also changes.
Closes zcash/librustzcash#1407.
Closes zcash/librustzcash#1408.

Migrate from `hdwallet` to `bip32`

---

.vscode/settings.json

This setting is no longer required, and its presence greatly increases build and test times while using VS Code extensions for rust because inconsistent settings are used, defeating the rust build cache.

Drop orchard unstable flag from VS Code settings

---

zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/db.rs
zcash_client_sqlite/src/wallet/init.rs

The existing pins for the current database structure are moved out of the `verify_schema` test, so they can serve the dual purpose of documentating the database structure.
The documentation needs significantly more detail than this PR currently includes; this is intended as a starting point from which we can continually improve our documentation going forward.

zcash_client_sqlite: Start documenting the table structures

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/fees/common.rs
zcash_client_backend/src/fees/zip317.rs
zcash_client_sqlite/src/testing/pool.rs

`zcash_client_backend::{fixed,standard,zip317}::SingleOutputChangeStrategy` now implement a different strategy for choosing whether there will be any change, and its value. The aims are:
* Ensure that it is still possible to create fully transparent transactions with no change (this will be needed for ZIP 320). The `ChangeError::InsufficientFunds` error in this case should have a `required` field that reflects the additional amount needed, according to the fee calculated without an extra change output.
* Avoid leaking information about note amounts in some cases: an adversary that knew the number of external recipients and the sum of their outputs was able to learn the sum of the inputs if no change output was present.
* Defend against losing money by using `DustAction::AddDustToFee` with …

Improvements to the strategy implemented by `{fixed,standard,zip317}::SingleOutputChangeStrategy`

---

zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/init/migrations.rs
zcash_client_sqlite/src/wallet/init/migrations/add_account_birthdays.rs
zcash_client_sqlite/src/wallet/init/migrations/add_utxo_account.rs
zcash_client_sqlite/src/wallet/init/migrations/addresses_table.rs
zcash_client_sqlite/src/wallet/init/migrations/ensure_orchard_ua_receiver.rs
zcash_client_sqlite/src/wallet/init/migrations/full_account_ids.rs
zcash_client_sqlite/src/wallet/init/migrations/initial_setup.rs
zcash_client_sqlite/src/wallet/init/migrations/nullifier_map.rs
zcash_client_sqlite/src/wallet/init/migrations/orchard_received_notes.rs
zcash_client_sqlite/src/wallet/init/migrations/orchard_shardtree.rs
zcash_client_sqlite/src/wallet/init/migrations/sapling_memo_consistency.rs
zcash_client_sqlite/src/wallet/init/migrations/sent_notes_to_internal.rs
zcash_client_sqlite/src/wallet/init/migrations/shardtree_support.rs
zcash_client_sqlite/src/wallet/init/migrations/ufvk_support.rs
zcash_client_sqlite/src/wallet/init/migrations/utxos_table.rs
zcash_client_sqlite/src/wallet/init/migrations/v_sapling_shard_unscanned_ranges.rs
zcash_client_sqlite/src/wallet/init/migrations/v_transactions_shielding_balance.rs
zcash_client_sqlite/src/wallet/init/migrations/v_transactions_transparent_history.rs
zcash_client_sqlite/src/wallet/init/migrations/v_tx_outputs_use_legacy_false.rs
zcash_client_sqlite/src/wallet/init/migrations/wallet_summaries.rs

The `foreign_keys` pragma has no effect when used within a transaction, so it should only be set at the top level. The `legacy_alter_table` pragma should only be used in cases where its effect is explicitly intended.
Best reviewed hiding whitespace changes.

zcash_client_sqlite: Fix handling of PRAGMA directives.

---

Cargo.lock
Cargo.toml
zcash_client_backend/src/serialization/shardtree.rs

zcash_client_backend: Fix panic related to insertion of frontiers below subtree roots.

---

zcash_client_sqlite/src/testing.rs

These are only usable if both `#[cfg(test)]` and the "unstable" feature are enabled.

Add utility methods on `TestState` to dump the contents of a database table, or run an sqlite3 command

---

Cargo.lock
supply-chain/imports.lock
zcash_extensions/CHANGELOG.md
zcash_extensions/Cargo.toml

We are forced to publish this in order to secure the `zcash_extensions` crate name. crates.io changed their Usage Policy in November 2023 to prohibit name-squatting; my account was temporarily locked, and this crate deleted, because it only had a `0.0.0` reservation release with no code.

`zcash_extensions 0.1.0`

---

Cargo.lock
Cargo.toml
deny.toml
supply-chain/config.toml
supply-chain/imports.lock
zcash_client_backend/CHANGELOG.md
zcash_client_backend/Cargo.toml
zcash_client_backend/src/lib.rs
zcash_client_backend/src/tor.rs
zcash_client_backend/src/tor/http.rs
zcash_client_backend/src/tor/http/cryptex.rs
zcash_client_backend/src/tor/http/cryptex/binance.rs
zcash_client_backend/src/tor/http/cryptex/coinbase.rs
zcash_client_backend/src/tor/http/cryptex/gate_io.rs
zcash_client_backend/src/tor/http/cryptex/gemini.rs
zcash_client_backend/src/tor/http/cryptex/ku_coin.rs
zcash_client_backend/src/tor/http/cryptex/mexc.rs
zcash_client_sqlite/Cargo.toml

zcash_client_backend: Add a Tor client that can fetch USD/ZEC exchange rates

---

components/zcash_address/src/kind/unified.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet/scanning.rs
zcash_primitives/src/extensions/transparent.rs
zcash_primitives/src/legacy/keys.rs
zcash_primitives/src/transaction/fees/fixed.rs

remove duplicate words in comments to improve readability.

chore: remove duplicate words

---

Cargo.lock
Cargo.toml
devtools/Cargo.toml
devtools/src/bin/inspect/address.rs
devtools/src/bin/inspect/block.rs
devtools/src/bin/inspect/context.rs
devtools/src/bin/inspect/keys.rs
devtools/src/bin/inspect/main.rs
devtools/src/bin/inspect/transaction.rs
supply-chain/config.toml
supply-chain/imports.lock
zcash_primitives/src/transaction/components/tze.rs
zcash_proofs/Cargo.toml

Given that we are working to deprecate `zcashd`, I figure we should move this tool out of its repository. I've also augmented it with P2PKH-TEX conversions.

Import `zcash-inspect` from `zcash/zcash` into a `devtools` crate

---

Cargo.lock
devtools/Cargo.toml
devtools/src/bin/inspect/lookup.rs
devtools/src/bin/inspect/main.rs
devtools/src/bin/inspect/transaction.rs
supply-chain/config.toml

This queries `lightwalletd` for things that might be txids, and could be extended to other queryable formats in future.

devtools: Add `--lookup` argument to `zcash-inspect`

---

zcash_primitives/src/transaction/components/transparent.rs

This doesn't affect the public API, but it improves the `Debug` impl for `OutPoint` because `TxId` renders its `[u8; 32]` as byte-reversed hex.

zcash_primitives: Use `TxId` type inside `transparent::OutPoint`

---

.vscode/settings.json

This is necessary because the Rust version from `rust-toolchain.toml` is too old for the current proc-macros protocol (specifically, the `--keep-going` flag was not stable in Rust 1.70, as can be verified by `cargo +1.70.0 check --keep-going`).
This works around https://github.com/rust-lang/rust-analyzer/issues/17662 , and very likely future problems, because the rust-analyzer devs are quite aggressive in depending on recent versions: "by policy we don't make any attempts at supporting more than the last couple of stable releases" according to https://github.com/rust-lang/rust-analyzer/issues/17662#issuecomment-2242265513 . The toolchain we select in `rust-toolchain.toml` often lags behind that intentionally, because we want to verify that we build with our MSRV.

Tell rust-analyzer to compile using stable

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/wallet.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet.rs

This provides more robust transactionality in case a call to `store_sent_tx` (now renamed to `store_transaction_to_be_sent`) fails for a step of a multi-step proposal after the first.

Use a single database transaction when storing transactions to be sent

---

zcash_client_backend/src/data_api.rs
zcash_client_sqlite/src/wallet/init/migrations/ephemeral_addresses.rs

Post #1425 fixes

---

components/zcash_protocol/src/consensus.rs
components/zcash_protocol/src/local_consensus.rs
zcash_client_sqlite/src/testing.rs
zcash_extensions/src/transparent/demo.rs
zcash_primitives/src/transaction/mod.rs

We want to add the [testnet network activation to Zebra](https://github.com/ZcashFoundation/zebra/issues/8689) but we need the same in `zcash_primitives`. We also need to remove the `zcash_unstable = "nu6"` feature.

Make `nu6` rust feature stable

---

zcash_client_backend/src/data_api.rs
zcash_client_sqlite/src/error.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet.rs

When adding an account, check whether any component of its UFVK (if available) collides with an existing imported or derived FVK.
This does not check for collisions on IVK for `Incoming` accounts (#1490), which is okay because those are not yet exposed in the public API.
Builds on #1479, fixes #1474

Check for colliding component FVKs

---

zcash_client_backend/src/data_api/wallet/input_selection.rs
zcash_client_sqlite/Cargo.toml
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/init/migrations/ensure_orchard_ua_receiver.rs
zcash_client_sqlite/src/wallet/init/migrations/ephemeral_addresses.rs
zcash_client_sqlite/src/wallet/init/migrations/full_account_ids.rs
zcash_keys/src/address.rs
zcash_keys/src/keys.rs

Ensure that `zcash_client_sqlite` only enables "orchard" for `zcash_keys` when its own "orchard" feature is enabled

---

zcash_client_sqlite/src/testing/pool.rs

Trivial doc-only follow-up to #1473.

Improve the accuracy of a comment in `send_multi_step_proposed_transfer`

---

Cargo.lock
Cargo.toml
components/zcash_address/CHANGELOG.md
components/zcash_address/Cargo.toml
supply-chain/audits.toml
supply-chain/imports.lock

zcash_address: release version 0.4.0

---

Cargo.lock
Cargo.toml
zcash_client_backend/Cargo.toml
zcash_client_backend/src/tor.rs
zcash_client_backend/src/tor/grpc.rs
zcash_client_backend/src/tor/http.rs

Closes zcash/librustzcash#1471.

zcash_client_backend: Add `tor::Client::connect_to_lightwalletd`

---

components/zcash_protocol/CHANGELOG.md
components/zcash_protocol/src/consensus.rs

These operations are unused, and it does not make sense to add block heights (or to subtract two block heights returning a block height).

zcash_protocol: Remove impl {Add, Sub} for BlockHeight

---

components/zcash_protocol/CHANGELOG.md
components/zcash_protocol/src/consensus.rs

In contrast to the implementation of `Sub<BlockHeight> for BlockHeight` that was removed in version `0.3.0`, a saturating subtraction for block heights having a return type of `u32` makes sense for `BlockHeight`. Subtracting one block height from another yields the delta between them.
Other block height addition and subtraction operations have been made saturating, removing panics and the possibility of overflow.

Add correct `BlockHeight` subtraction & remove panics.

---

zcash_client_backend/src/fees/fixed.rs
zcash_client_backend/src/fees/standard.rs
zcash_client_backend/src/fees/zip317.rs

Thanks to @AArnott for pointing out the inaccuracy.

Make the `{fixed,standard,zip317}::SingleOutputChangeStrategy` doc comments more accurate concerning the choice of output pool

---

zcash_client_sqlite/src/wallet/transparent/ephemeral.rs

The `reserve_until` method for generating ephemeral addresses is used in database migrations, but it makes no sense to use this in the case that the UFVK for an account contains no transparent component; such accounts can never be used to make ZIP 320 spends.

zcash_client_sqlite: Do not require a transparent key for migrations.

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/Cargo.toml
zcash_client_backend/src/tor.rs

We already depend on `rustls` and `webpki-roots` for `tor::http`, but `tonic` has its own feature flag that needs to be enabled for equivalent support in `tor::grpc`. We didn't need that feature flag enabled for the `proto::service::compact_tx_streamer_client` module because those constructors take a `D: TryInto<tonic::transport::Endpoint>`, which abstracts over TLS and leaves it up to the caller. By constrast, in `tor::grpc` we need to construct the `Endpoint` manually from a `Uri` and then configure TLS ourselves.

zcash_client_backend: Fix `tor::grpc` module feature flag

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/testing/pool.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/scanning.rs

We now split progress into "scan progress" and "recover progress" based on the recover-until height (if set, otherwise recover progress is always 100%).
Part of #1070.

Improve progress representation in `WalletSummary`

---

zcash_client_sqlite/CHANGELOG.md

Closes zcash/librustzcash#1525.

Document the change to `v_tx_outputs` in `zcash_client_sqlite 0.11.0`

---

components/zcash_protocol/CHANGELOG.md
components/zcash_protocol/src/consensus.rs

zcash_protocol: Set the public mainnet activation height for NU6

---

zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/src/lib.rs

This is necessary for third parties using the `zcash_client_sqlite` crate directly to be able to refer to individual account IDs without having to always use FVKs to look them up.

zcash_client_sqlite: Add unstable conversions between `AccountId` and `u32`.

---

Cargo.lock
supply-chain/imports.lock
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/testing/pool.rs
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/Cargo.toml
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/scanning.rs

This ensures that we use `recover_until_height` as an exclusive end height, and makes sure that we are estimating tree size based upon consistent heights between the recovery and scan ranges.

zcash_client_sqlite: Fix errors in progress computation.

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/testing/pool.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/scanning.rs

In zcash_client_backend 0.14, the semantics of the `WalletSummary::scan_progress` method changed silently, which could lead to unwary users getting bad results for scan progress, in particular, an indication that scanning is complete when there is still a substantial amount of recovery still needed.
In addition, the type of the `WalletSummary::scan_progress` and `recovery_progress` methods incorrectly make the state where recovery progress information is available, but scan progress information is not available, representable. 
This PR introduces a breaking API change that is intended to reduce the possibility of incorrect usage, and correctly represent the possible states of scanning and recovery.

zcash_client_backend: Return scan and restore progress as a single value.

---

components/zcash_protocol/CHANGELOG.md
components/zcash_protocol/src/value.rs
zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/error.rs
zcash_client_backend/src/data_api/testing.rs
zcash_client_backend/src/data_api/testing/pool.rs
zcash_client_backend/src/data_api/testing/transparent.rs
zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/data_api/wallet/input_selection.rs
zcash_client_backend/src/fees.rs
zcash_client_backend/src/fees/common.rs
zcash_client_backend/src/fees/fixed.rs
zcash_client_backend/src/fees/standard.rs
zcash_client_backend/src/fees/zip317.rs
zcash_client_backend/src/proposal.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/testing/pool.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/common.rs
zcash_client_sqlite/src/wallet/orchard.rs
zcash_client_sqlite/src/wallet/sapling.rs
zcash_client_sqlite/src/wallet/scanning.rs
zcash_keys/src/keys.rs

Best reviewed commit-by-commit, hiding whitespace changes.

zcash_client_backend: Implement note management via change splitting.

---

zcash_client_backend/src/data_api/testing/pool.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/testing/db.rs
zcash_client_sqlite/src/testing/pool.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/init/migrations.rs
zcash_client_sqlite/src/wallet/init/migrations/fix_bad_change_flagging.rs
zcash_client_sqlite/src/wallet/orchard.rs
zcash_client_sqlite/src/wallet/sapling.rs
zcash_client_sqlite/src/wallet/scanning.rs
zcash_client_sqlite/src/wallet/transparent.rs

zcash_client_sqlite: Ensure that all shielded change outputs are correctly flagged.

---

.github/workflows/audits.yml
.github/workflows/book.yml
.github/workflows/ci.yml

This enables us to add a single "required status check" to the GitHub repo settings, that covers all required matrix job cases.

CI: Add a job that runs when all required status checks pass

---

Cargo.lock
Cargo.toml
supply-chain/config.toml
zcash_client_backend/CHANGELOG.md
zcash_client_backend/Cargo.toml
zcash_client_backend/src/tor/http/cryptex.rs
zcash_client_backend/src/tor/http/cryptex/binance.rs
zcash_client_backend/src/tor/http/cryptex/coinbase.rs
zcash_client_backend/src/tor/http/cryptex/gate_io.rs
zcash_client_backend/src/tor/http/cryptex/gemini.rs
zcash_client_backend/src/tor/http/cryptex/ku_coin.rs
zcash_client_backend/src/tor/http/cryptex/mexc.rs

RPIT (return-position `impl Trait`) was stabilized in Rust 1.75, and the `dynosaur` crate providing dynamic dispatch support was published two weeks ago. Now that our MSRV is 1.77, we can use both of these.

zcash_client_backend: Switch from `async-trait` to RPIT for `tor` module

---

zcash_client_backend/src/data_api.rs

* Fix the documentation for `find_account_for_ephemeral_address` which included a use of `get_known_ephemeral_addresses` with incorrect types.
* Clarify that passing `None` for the `index_range` parameter of `get_known_ephemeral_addresses` is equivalent to passing `0..(1u32 << 31)`.

[doc-only] Minor documentation fix and clarification for the data API

---

.github/workflows/ci.yml
Cargo.lock
zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/testing.rs
zcash_client_backend/src/data_api/testing/pool.rs
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/Cargo.toml
zcash_client_sqlite/src/error.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/testing/db.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/common.rs
zcash_client_sqlite/src/wallet/db.rs
zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/init/migrations.rs
zcash_client_sqlite/src/wallet/init/migrations/add_account_uuids.rs
zcash_client_sqlite/src/wallet/init/migrations/ephemeral_addresses.rs
zcash_client_sqlite/src/wallet/init/migrations/fix_bad_change_flagging.rs
zcash_client_sqlite/src/wallet/init/migrations/full_account_ids.rs
zcash_client_sqlite/src/wallet/init/migrations/receiving_key_scopes.rs
zcash_client_sqlite/src/wallet/init/migrations/tx_retrieval_queue.rs
zcash_client_sqlite/src/wallet/orchard.rs
zcash_client_sqlite/src/wallet/sapling.rs
zcash_client_sqlite/src/wallet/scanning.rs
zcash_client_sqlite/src/wallet/transparent.rs
zcash_client_sqlite/src/wallet/transparent/ephemeral.rs

This provides equivalent uniqueness to the `accounts` table primary key, but avoids collisions across wallet recreation events (to defend against downstream crate users who don't flush any persisted account IDs at those events).
Closes #1629.

zcash_client_sqlite: Assign UUIDs to each account

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/testing/transparent.rs
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/transparent.rs

[#1411] Refactor AccountBalance to use Balance for transparent funds

---

zcash_client_sqlite/src/wallet/db.rs
zcash_client_sqlite/src/wallet/init/migrations/add_account_uuids.rs

`v_tx_outputs` gains new JOINs on `accounts.id` in order to migrate to exposing `accounts.uuid`, but as there are two table joins the tables are given aliases. The aliases were not being used in the JOIN's ON condition, leading to an error when querying the view.

zcash_client_sqlite: Fix `add_account_uuids` migration

---

zcash_client_sqlite/src/wallet/db.rs
zcash_client_sqlite/src/wallet/init/migrations/add_account_uuids.rs

Review ignoring whitespace changes.

zcash_client_sqlite: Fix incorrect column names in `v_tx_outputs` view.

---

Cargo.lock
Cargo.toml
pczt/src/roles.rs
pczt/src/roles/signer/mod.rs
pczt/src/roles/verifier/mod.rs
pczt/src/roles/verifier/orchard.rs
pczt/src/roles/verifier/sapling.rs
pczt/src/roles/verifier/transparent.rs
zcash_primitives/src/transaction/components/transparent/pczt.rs
zcash_primitives/src/transaction/components/transparent/pczt/verify.rs

This isn't a real role per se; it's instead a way for accessing the parsed protocol-specific bundles for individual access and verification.

pczt: Add a Verifier role

---

Cargo.lock
components/zcash_protocol/CHANGELOG.md
components/zcash_protocol/Cargo.toml
components/zcash_protocol/src/consensus.rs
components/zcash_protocol/src/lib.rs
components/zcash_protocol/src/memo.rs
components/zcash_protocol/src/value.rs
supply-chain/audits.toml
supply-chain/imports.lock

This enables these crates to be used in environments like hardware wallets.

Only require `alloc` instead of `std` where useful

---

Cargo.lock
Cargo.toml
pczt/src/orchard.rs
pczt/src/sapling.rs
pczt/src/transparent.rs
zcash_client_backend/src/data_api/wallet.rs
zcash_primitives/src/transaction/components/transparent/builder.rs
zcash_primitives/src/transaction/components/transparent/pczt.rs
zcash_primitives/src/transaction/components/transparent/pczt/parse.rs
zcash_primitives/src/transaction/components/transparent/pczt/updater.rs

This is necessary in order for Signers to display the address encoding that a user is expecting to confirm.

pczt: Add output field for storing the user-facing address

---

Cargo.lock
Cargo.toml
components/zcash_protocol/Cargo.toml
components/zip321/Cargo.toml
zcash_primitives/Cargo.toml
zcash_transparent/CHANGELOG.md
zcash_transparent/Cargo.toml
zcash_transparent/src/address.rs
zcash_transparent/src/bundle.rs
zcash_transparent/src/keys.rs
zcash_transparent/src/lib.rs

Also adds a new method that the Keystone firmware requires.

zcash_transparent: Fix its dependencies to work with no-std

---

Cargo.lock
Cargo.toml
components/zcash_encoding/CHANGELOG.md
pczt/CHANGELOG.md
supply-chain/audits.toml
supply-chain/config.toml
supply-chain/imports.lock
zcash_client_backend/CHANGELOG.md
zcash_client_sqlite/CHANGELOG.md
zcash_keys/CHANGELOG.md
zcash_keys/Cargo.toml
zcash_keys/src/encoding.rs
zcash_keys/src/keys.rs
zcash_keys/src/lib.rs
zcash_primitives/CHANGELOG.md

This cannot be merged until we have `nonempty` and `orchard` releases that support `no_std`

zcash_keys: Enable `no_std` usage.

---

zcash_client_backend/src/sync.rs

The bug was fixed in zcash/lightwalletd@b805382ac34e91678ed0d06e9c5f84187ac630cc, and the workaround doesn't work with backed by zebrad.

zcash_client_backend: Remove lightwalletd workaround

---

Cargo.lock
zcash_extensions/Cargo.toml
zcash_extensions/src/transparent/demo.rs
zcash_primitives/src/extensions/transparent.rs
zcash_primitives/src/transaction/builder.rs
zcash_primitives/src/transaction/components/tze.rs
zcash_primitives/src/transaction/components/tze/builder.rs
zcash_primitives/src/transaction/fees/tze.rs

This fixes a few errors that have been introduced over time since `zcash_extensions` is not regularly built, and migrates `zcash_extensions` to eliminate the use of deprecated `zcash_primitives` APIs.

zcash_extensions: Fix build errors following value changes to `zcash_protocol`

---

zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/src/lib.rs

This enables downstream wallets such as Zallet to implement connection pooling, or other strategies to enable multi-threaded `WalletDb` access.

zcash_client_sqlite: Enable constructing `WalletDb` around references to `rusqlite::Connection`

---

Cargo.lock
Cargo.toml
zcash_client_backend/CHANGELOG.md
zcash_client_backend/Cargo.toml
zcash_client_backend/src/tor.rs

Closes zcash/librustzcash#1686.

zcash_client_backend: Allow disabling Tor directory permissions tightening

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/tor.rs

The optional closure was requiring a type annotation when using `None`, which would create a more complex API than just passing an empty closure.

zcash_client_backend: Fix `tor::Client::create` argument

---

Cargo.lock
components/equihash/CHANGELOG.md
components/equihash/Cargo.toml
components/equihash/src/lib.rs
components/zcash_address/src/lib.rs
components/zcash_protocol/src/consensus.rs
pczt/CHANGELOG.md
pczt/Cargo.toml
pczt/README.md
pczt/src/common.rs
pczt/src/lib.rs
pczt/src/orchard.rs
pczt/src/roles.rs
pczt/src/roles/combiner/mod.rs
pczt/src/roles/creator/mod.rs
pczt/src/roles/io_finalizer/mod.rs
pczt/src/roles/low_level_signer/mod.rs
pczt/src/roles/prover/mod.rs
pczt/src/roles/redactor/mod.rs
pczt/src/roles/signer/mod.rs
pczt/src/roles/spend_finalizer/mod.rs
pczt/src/roles/tx_extractor/mod.rs
pczt/src/roles/updater/mod.rs
pczt/src/roles/verifier/mod.rs
pczt/src/sapling.rs
pczt/src/transparent.rs
supply-chain/imports.lock
zcash_keys/src/lib.rs

This PR includes patch releases of `equihash` and `pczt`, for which their public documentation omits significant parts of their APIs (due to not being built with `--all-features`). The rest of the fixes don't appear to affect the public doc builds, they are just local issues I noticed while fixing the other two.

Fix crate documentation

---

zcash_client_backend/src/fees/common.rs
zcash_client_backend/src/fees/zip317.rs

Best reviewed hiding whitespace. Split diff rather than unified helps also.

zcash_client_backend: Fix errors in change computation for wallet-emptying transactions.

---

zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/commitment_tree.rs
zcash_client_sqlite/src/wallet/common.rs
zcash_client_sqlite/src/wallet/orchard.rs
zcash_client_sqlite/src/wallet/sapling.rs

This functionality is needed in order to make it possible for wallets that have corrupted note commitment tree state to recover from that situation.

zcash_client_sqlite: Add methods for fixing broken note commitment trees.

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api/testing/pool.rs
zcash_client_backend/src/data_api/wallet.rs
zcash_client_backend/src/decrypt.rs
zcash_client_sqlite/src/wallet/init/migrations/receiving_key_scopes.rs
zcash_client_sqlite/src/wallet/init/migrations/sapling_memo_consistency.rs

This fixes https://github.com/zcash/librustzcash/issues/1746, which made it possible for `zcash_client_backend::decrypt_and_store_transaction` to incorrectly set a `mined_height` value for a mempool transaction.

zcash_client_backend: Fix zcash/librustzcash#1746

---

Cargo.lock
supply-chain/config.toml
supply-chain/imports.lock
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/Cargo.toml
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/init/migrations.rs
zcash_client_sqlite/src/wallet/init/migrations/ensure_default_transparent_address.rs
zcash_client_sqlite/src/wallet/init/migrations/transparent_gap_limit_handling.rs
zcash_client_sqlite/src/wallet/transparent.rs
zcash_transparent/CHANGELOG.md
zcash_transparent/Cargo.toml
zcash_transparent/src/keys.rs

Earlier versions of the `zcash_client_sqlite` wallet did not store the transparent addresses at child indices prior to the diversifier index of the first unified address in the `addresses` table. This caused an error in migration for wallets that had received outputs at the address with child index 0, likely because they imported a seed generated by a wallet that had previously exposed that address.

zcash_client_sqlite: Fix migration error caused by missing transparent addresses prior to the index of the default address

---

Cargo.lock
Cargo.toml
zcash_client_backend/Cargo.toml

This pins `time-core` to version `0.1.2` to work around https://anonticket.torproject.org/user/projects/arti/issues/pending/4028/

Pin `time-core` to workaround `deranged` impl conflict.

---

zcash_client_backend/proto/service.proto
zcash_client_backend/src/proto/service.rs

In order to encourage more people to run light wallet servers, this change allows operators to specify a donation address for users and grantors to contribute to the server operator's expenses.
Related PRs:
- [Zingolib #1660](https://github.com/zingolabs/zingolib/pull/1660)
- [Zaino #185](https://github.com/zingolabs/zaino/pull/185)
- [Lightwalletd #506](https://github.com/zcash/lightwalletd/pull/506)

Add Donation Address to gRPC LightdInfo

---

.github/actions/prepare/action.yml
.github/workflows/ci.yml
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet/init/migrations.rs
zcash_client_sqlite/src/wallet/init/migrations/fix_transparent_received_outputs.rs

Previously, in CI we were:
- Not enabling the `orchard` feature flag for our regular builds and linters.
- Always enabling the `transparent-inputs` feature flag for our tests.
These led to bugs being missed, and deployed to production. We now always build/lint with all pool-specific feature flags enabled, and we test with more flag combinations.
This PR also corrects a problem in zcash_client_sqlite with the `transparent_gap_limit_handling` migration only having been run when the `transparent-inputs` feature flag enabled. It should have been run unconditionally. We also make some other doc and test fixes to zcash_client_sqlite.

zcash_client_sqlite migration and doc fixes; also CI: fix bugs related to pool feature flag combinations

---

zcash_client_backend/CHANGELOG.md
zcash_client_backend/src/data_api.rs
zcash_client_backend/src/data_api/testing.rs
zcash_client_backend/src/data_api/testing/orchard.rs
zcash_client_backend/src/data_api/testing/pool.rs
zcash_client_backend/src/data_api/testing/sapling.rs
zcash_client_backend/src/data_api/wallet/input_selection.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/testing/db.rs
zcash_client_sqlite/src/wallet/common.rs
zcash_client_sqlite/src/wallet/orchard.rs
zcash_client_sqlite/src/wallet/sapling.rs

Working towards enabling `send_max_funds`.
Said @nuttycom over discord:
> We can also just chat here: right now, the main impediment to the approach suggested above is that https://docs.rs/zcash_client_backend/latest/zcash_client_backend/data_api/trait.InputSource.html#tymethod.select_spendable_notes requires a target value. We'll likely need to change the API of this method to make the target value a bespoke enum with variants `pub enum TargetValue {MaxSpendable, MinValue(Zatoshis)}`. We could alternately add a separate method, but I think that changing to use an enum for the target value is better.
My idea is to start implementing this in the most non-breaking way as possible. 
``` rust
#[derive(Debug, Clone, Copy)]
pub enum TargetValue {
MaxSpendable,
MinValue(Zatoshis)
} 
```
The Send …

Define `TargetValue` to select spendable notes

---

components/zcash_address/CHANGELOG.md
components/zcash_address/src/convert.rs
components/zcash_address/src/kind/unified/address.rs
components/zcash_address/src/lib.rs
zcash_keys/CHANGELOG.md
zcash_keys/src/address.rs
zcash_transparent/CHANGELOG.md
zcash_transparent/src/address.rs

The functionality of `TryFromRawAddress` impls can be entirely subsumed by `TryFromAddress` impls that simply ignore the `net` argument; the removed type added interface complexity that has presented a stumbling block to users of the API.

zcash_address: Removes `TryFromRawAddress`

---

components/zcash_address/src/lib.rs

Close https://github.com/zcash/librustzcash/issues/1769
I ran a project-wide search for "zs1z7rejlpsa98s2rrrfkwmaxu53e4ue0ulcrw0h4x5g8jl04tak0d3mm47vdtahatqrlkngh9sly" and this is the only occurrence, so no other updates are needed.

Fix `try_from_encoded` example address

---

README.md

Added link to free2z-hosted 'Rust Crates Walkthrough' w/ nuttycom in the README.

free2z-hosted 'Rust Crates Walkthrough' w/ nuttycom

---

zcash_history/CHANGELOG.md
zcash_history/src/entry.rs
zcash_history/src/version.rs

As discussed on discord, I am working on implementing flyclient prover functionalities into zebrad. Because zebrad's implementation of history trees uses `Entry` as the type for nodes, it would be useful to have access to its inner `NodeData`, to avoid having to operate on the serialized bytes directly. This is needed especially when reading nodes from the database and sending them to clients.

zcash_history: allow to return `V::NodeData` from `Entry`

---

zcash_client_backend/src/data_api.rs
zcash_client_sqlite/src/lib.rs
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/transparent.rs

Prior to this change, `decrypt_and_store_transaction` would erroneously create a record in the `transactions` table, even if the transaction didn't involve the wallet at all.

zcash_client_sqlite: Do not store a transaction record if there is no wallet involvement.

---

Cargo.lock
Cargo.toml
components/zcash_address/CHANGELOG.md
components/zcash_address/Cargo.toml
components/zcash_protocol/CHANGELOG.md
components/zcash_protocol/Cargo.toml
components/zip321/CHANGELOG.md
components/zip321/Cargo.toml
pczt/CHANGELOG.md
pczt/Cargo.toml
supply-chain/audits.toml
supply-chain/imports.lock
zcash_client_backend/CHANGELOG.md
zcash_client_backend/Cargo.toml
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/Cargo.toml
zcash_keys/CHANGELOG.md
zcash_keys/Cargo.toml
zcash_primitives/CHANGELOG.md
zcash_primitives/Cargo.toml
zcash_proofs/CHANGELOG.md
zcash_proofs/Cargo.toml
zcash_transparent/CHANGELOG.md
zcash_transparent/Cargo.toml

Releases of the following crates are included:
* zcash_protocol 0.5.2
* zcash_address 0.8.0
* zip321 0.4.0
* zcash_transparent 0.3.0
* zcash_primitives 0.23.0
* zcash_proofs 0.23.0
* zcash_keys 0.9.0
* pczt 0.3.0
* zcash_client_backend 0.19.0
* zcash_client_sqlite 0.17.0

Releases supporting `zcash_client_backend 0.19.0`

---

zcash_client_backend/src/data_api/testing/pool.rs
zcash_client_sqlite/CHANGELOG.md
zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/db.rs
zcash_client_sqlite/src/wallet/init/migrations.rs
zcash_client_sqlite/src/wallet/init/migrations/tx_retrieval_queue.rs
zcash_client_sqlite/src/wallet/init/migrations/tx_retrieval_queue_expiry.rs

`TransactionDataRequest::GetStatus` requests for txids that do not correspond to unexpired transactions in the transactions table will now be deleted from the status check queue when `set_transaction_status` is called with a status of either `TxidNotRecognized` or `NotInMainChain`.

zcash_client_sqlite: Ensure unsatisfiable tx status requests get deleted.

---

Cargo.lock
Cargo.toml
components/zcash_protocol/CHANGELOG.md
components/zcash_protocol/Cargo.toml
components/zcash_protocol/src/consensus.rs
components/zcash_protocol/src/constants.rs
components/zcash_protocol/src/constants/mainnet.rs
components/zcash_protocol/src/constants/testnet.rs
components/zcash_protocol/src/local_consensus.rs
components/zcash_protocol/src/txid.rs
pczt/Cargo.toml
pczt/src/lib.rs
pczt/src/roles/creator/mod.rs
pczt/src/roles/io_finalizer/mod.rs
pczt/src/roles/signer/mod.rs
pczt/src/roles/tx_extractor/mod.rs
zcash_client_backend/src/data_api/testing.rs
zcash_client_sqlite/src/wallet/init.rs
zcash_client_sqlite/src/wallet/init/migrations/add_transaction_views.rs
zcash_client_sqlite/src/wallet/init/migrations/tx_retrieval_queue.rs
zcash_primitives/CHANGELOG.md
zcash_primitives/src/transaction/mod.rs
zcash_primitives/src/transaction/sighash.rs

The `zcash_protocol-0.5.x` branch was produced based on a state of the `main` branch that contains SemVer breaking changes relative to the crates used on the `zcash_client_sqlite-0.16.x` branch. This backport makes it possible to make further SemVer point-release compatible changes to `zcash_protocol-0.5.x` and use those changes in `zcash_client_sqlite-0.16.x`. Any such changes should be made first on the `zcash-protocol-0.5.x` branch, and then backported in the same fashion (using `git cherry-pick -x`) as the commits being backported by this PR.

Backport changes from `zcash_protocol-0.5.x` to `zcash_client_sqlite-0.16.x` branch.

---

Cargo.lock
Cargo.toml
components/zcash_protocol/CHANGELOG.md
components/zcash_protocol/Cargo.toml
components/zcash_protocol/src/txid.rs
components/zcash_protocol/src/value.rs
supply-chain/audits.toml
supply-chain/config.toml
supply-chain/imports.lock
zcash_client_backend/src/tor/http/cryptex.rs
zcash_history/src/tree.rs
zcash_primitives/CHANGELOG.md
zcash_primitives/Cargo.toml
zcash_primitives/src/transaction/builder.rs
zcash_transparent/src/bundle.rs

The newly created `Add` impl's in `zcash_protocol 0.5.4` cause build failures of `zcash_primitives 0.23.0` due to an incautious use of `.into()` in the `zcash_primitives` codebase. This release remedies that error.

Release zcash_primitives 0.23.1

---

Cargo.lock
Cargo.toml
zcash_keys/CHANGELOG.md
zcash_keys/Cargo.toml
zcash_keys/src/keys.rs

`zcash_keys::keys::{UnifiedFullViewingKey, UnifiedIncomingViewingKey}::default_transparent_address` have been added under the `test-dependencies` feature.
Note that once this PR has the required approving reviews, it will be closed via merge as part of #1862

zcash_keys: Add test-dependencies feature methods for taddr retrieval.

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
zcash_client_backend/CHANGELOG.md
zcash_client_backend/Cargo.toml
zcash_client_backend/src/data_api/testing.rs
zcash_client_backend/src/data_api/testing/pool.rs
zcash_client_sqlite/src/wallet/scanning.rs
zcash_keys/CHANGELOG.md
zcash_keys/Cargo.toml
zcash_keys/src/address.rs
zcash_keys/src/keys.rs

The existing type signature of this method made it impossible to use it with a proposal created by `zcash_client_backend::data_api::wallet::propose_shielding`.
This is technically a semver-breaking change, but as it only affects test code under the `test-dependencies` feature flag, it's worth it to include this in a patch release.
Once it has an approving review, this PR will merge as part of #1862

zcash_client_backend: Fix overly-constrained type signature of TestState::create_proposed_transaction

---

.github/workflows/ci.yml

We recently found that a test failure was sneaking past CI because cargo features configured it out. This adds a workflow job to test with `--all-features`, which should catch this case in the future.

fix: add --all-features test to CI

---

.github/actions/prepare/action.yml
.github/workflows/audits.yml
.github/workflows/book.yml
.github/workflows/ci.yml
.github/workflows/zizmor.yml

* Narrow the permissions granted to CI steps (fixing a zizmor warning).
* CI refactoring:
* Make 'all-features' a variable allowing it to be enabled for any job.
* Make the 'all-features' tests required-to-pass on Linux.
* Also test with 'all-features' on Windows.
* Enable the "transparent-key-encoding" feature whenever "transparent-inputs" is enabled.
* Fix documentation links.
* Correctly document the version of `actions/checkout` used by `zizmor.yml`.
* Use SHA references for GitHub actions from sources other than official GitHub namespaces and the Rust toolchains (`todtolnay/rust-toolchain@*`).

Narrow the permissions granted to CI steps and other CI refactoring

---

zcash_client_sqlite/src/wallet.rs

After zcash/librustzcash#1813 we don't store every transaction that this method is called with, but still logged that we were.

zcash_client_sqlite: Fix logging in `store_decrypted_tx`

---

zcash_client_sqlite/src/wallet.rs
zcash_client_sqlite/src/wallet/db.rs
zcash_client_sqlite/src/wallet/encoding.rs
zcash_client_sqlite/src/wallet/init/migrations/support_zcashd_wallet_import.rs

We can't have `zcashd_legacy_address_index` be a nullable column, as that would permit multiple accounts with the same values for `(hd_seed_fingerprint, hd_account_index)` because every `NULL` is treated as unique. Instead we use -1 as a sentinel.
Closes zcash/librustzcash#1948.

zcash_client_sqlite: Fix `hd_account` uniqueness constraint

---

components/zcash_protocol/src/lib.rs

Nightly rustdoc removed `doc_auto_cfg` and folded its functionality into the `doc_cfg` work: [RFC 3631](https://github.com/rust-lang/rfcs/blob/master/text/3631-rustdoc-cfgs-handling.md).
This crate still gated on `#![feature(doc_auto_cfg)]`, which causes docs.rs to fail on current nightly.
Here's [the original PR](https://github.com/rust-lang/rust/pull/138907).

docs(`zcash_protocol`): use `doc_cfg` instead of `doc_auto_cfg`
